### ISSUE TITLE
connection limits

### ISSUE THREAD

**Issue by flihp** [tpm2-software/tpm2-abrmd#197]
As a means to limit DoS on the tabrmd I'm thinking it may be useful to limit the number of connections any single client can make. With the DBus IPC front end we'd use PID to identify clients. When we add the TCP / IP / TLS front end we could use IP address instead?

**Comment by lugong** [comment]
Currently the design is using IP address+port to distinguish a connection from client.

**Comment by flihp** [comment]
Adding this to the 2.0 milestone. Exit criteria is verification that all of the following command line options work as expected: `--max-connections`, `--max-sessions`, `--max-transient-objects`.

**Comment by flihp** [comment]
`--max-connections` works but it is a system wide max, not per-client (see `$(srcdir)/test/integration/tcti-connections-max.int.c`). Imposing a per-client max would take some re-work so I'll create a new issue for this.

**Comment by flihp** [comment]
The test for `--max-transient-objects` is hiding in `$(srcdir)/integration/create-keys.int.c`. This test creates some number of keys under the NULL hierarchy. The number of keys created is determined by an environment variable or on the command line. This isn't particularly well integrated with the test harness and it doesn't look like this actually tests the upper bound on the number of transient objects a client is allowed to create. This deserves an issue of it's own.

**Comment by flihp** [comment]
This has been superseded by #453, #456, and #459.
