### ISSUE TITLE
Unit test for dbus TCTI requires access to dbus

### ISSUE THREAD

**Issue by flihp** [tpm2-software/tpm2-abrmd#303]
The dbus interaction should be `mock`ed away. No unit tests should access external resource like this.

**Comment by smcv** [comment]
To get the most thorough possible test coverage, using the real dbus-daemon is probably still a good idea. You can get a temporary dbus-daemon by wrapping your test with dbus-run-session(1), like dbus-python does:

https://gitlab.freedesktop.org/dbus/dbus-python/blob/dbus-python-1.2.8/Makefile.am#L220

or by running a dbus-daemon directly, like flatpak does, and directing its `--print-address` and optionally `--print-pid` file descriptors to files or pipes:

https://github.com/flatpak/flatpak/blob/1.0.3/tests/libtest.sh#L307

**Comment by flihp** [comment]
The unit tests now mock all interactions with dbus and can operation without dbus running. The integration tests remain unchanged using dbus in a way as close to a real deployment as possible.
