### ISSUE TITLE
session handling abrmd failures in tools

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-abrmd#317]
Recently we began seeing session issues in the extended session support:
See: https://api.travis-ci.org/v3/job/338122598/log.txt
```
<snip>
tests/send.sh ... PASSED

** (tpm2-abrmd:23004): WARNING **: Tss2_Sys_ContextLoad: failed to load context for context at: 0x7fd63401aae8, TSS2_RC: 0x1c4

** (tpm2-abrmd:23004): WARNING **: Failed to load context for session with handle 0x03000000 RC: 0x1c4

** (tpm2-abrmd:23004): WARNING **: Tss2_Sys_ContextLoad: failed to load context for context at: 0x7fd63401aae8, TSS2_RC: 0x1c4

** (tpm2-abrmd:23004): WARNING **: Failed to load context for session with handle 0x03000000 RC: 0x1c4

** (tpm2-abrmd:23004): WARNING **: Tss2_Sys_ContextLoad: failed to load context for context at: 0x7fd63401aae8, TSS2_RC: 0x1c4

** (tpm2-abrmd:23004): WARNING **: Failed to load context for session with handle 0x03000000 RC: 0x1c4

** (tpm2-abrmd:23004): WARNING **: Tss2_Sys_ContextLoad: failed to load context for context at: 0x7fd63401aae8, TSS2_RC: 0x1c4

** (tpm2-abrmd:23004): WARNING **: Failed to load context for session with handle 0x03000000 RC: 0x1c4

** (tpm2-abrmd:23004): WARNING **: Tss2_Sys_ContextLoad: failed to load context for context at: 0x7fd63401aae8, TSS2_RC: 0x1c4

** (tpm2-abrmd:23004): WARNING **: Failed to load context for session with handle 0x03000000 RC: 0x1c4

** (tpm2-abrmd:23004): WARNING **: Tss2_Sys_ContextLoad: failed to load context for context at: 0x7fd63401aae8, TSS2_RC: 0x1c4

** (tpm2-abrmd:23004): WARNING **: Failed to load context for session with handle 0x03000000 RC: 0x1c4

tests/nv.sh ... PASSED

tests/rsadecrypt.sh ... PASSED

tests/load.sh ... PASSED

tests/rc_decode.sh ... PASSED

tests/certify.sh ... PASSED

** (tpm2-abrmd:23004): WARNING **: Tss2_Sys_ContextLoad: failed to load context for context at: 0x7fd63401aae8, TSS2_RC: 0x1c4

** (tpm2-abrmd:23004): WARNING **: Failed to load context for session with handle 0x03000000 RC: 0x1c4
ERROR: PolicyPCR failed: 0x910
ERROR: Failed parse_policy_type_and_send_command
ERROR: Could not build pcr policy
tpm2_policypcr -Q -S $file_session_file -L ${alg_pcr_policy}:${pcr_ids} -F $file_pcr_value -f $file_policy on line 98 failed: 1
</snip>
```

**Comment by williamcroberts** [comment]
Starting a git bisect now to find where the issue is.

**Comment by williamcroberts** [comment]
Uhhh merge commits...

**Comment by flihp** [comment]
Your coverage is better than mine. I'll see if I can trigger something similar here to get some better coverage.

**Comment by flihp** [comment]
Also bisect is merge aware isn't it? Or are you saying the issue was introduced by a merge commit (likely manual fixups)?

**Comment by williamcroberts** [comment]
The problem is, when it follows a merge branch, it requires the older version of SAPI... so configure fails.

**Comment by williamcroberts** [comment]
I tried taking the patches and applying them to master directly so there is no rebase, but I was having issues. I just need to spend more time on that possible attempt.

**Comment by flihp** [comment]
Can you repro locally? I cannot. Logfile attached of a local test run with current master from all 3 projects. I can see the failures on travis-ci, just can't make it happen locally.
[test.log](https://github.com/tpm2-software/tpm2-abrmd/files/1704174/test.log)

**Comment by williamcroberts** [comment]
Your test.log file seems to show the issue.

I have the same log locally. Here is the abrmd output:
```
** (tpm2-abrmd:7284): WARNING **: Tss2_Sys_ContextLoad: failed to load context for context at: 0x7f20380033b8, TSS2_RC: 0x1c4

** (tpm2-abrmd:7284): WARNING **: Failed to load context for session with handle 0x03000000 RC: 0x1c4
```
Your log snippet:
```
ERROR: PolicyPCR failed: 0x910
ERROR: Failed parse_policy_type_and_send_command
ERROR: Could not build pcr policy
tpm2_policypcr -Q -S $file_session_file -L ${alg_pcr_policy}:${pcr_ids} -F $file_pcr_value -f $file_policy on line 98 failed: 1

tests/tcti/abrmd/extended-sessions.sh ... FAILED
Tests passed: 37
Tests Failed: 1
Fail summary:
```

FYI to skip the other tests do:
```
./test.sh tests/tcti/abrmd/extended-sessions.sh 
```
The error code decoded:
```
error layer
  hex: 0x0
  identifier: TSS2_TPM_RC_LAYER
  description: Error produced by the TPM
format 0 warning code
  hex: 0x10
  name: TPM2_RC_REFERENCE_H0
  description: the 1st handle in the handle area references a transient object or session that is not loaded
```

**Comment by williamcroberts** [comment]
For some reason my session handle is getting flushed. Is there a debug mode I can run tpm2-abrmd in?

**Comment by williamcroberts** [comment]
By debug I mean more in, seeing the commands hitting the tpm. Something like pcap for abrmd would be nice... I think we talked about that before, at least I talked to someone about something like that before.

Something like a verbose mode so I can see into what it is doing...

**Comment by williamcroberts** [comment]
@flihp bump, anything on this yet?

**Comment by flihp** [comment]
candidate fix is here: https://github.com/flihp/tpm2-abrmd/tree/new-sessions-on-loaded-session-list, test using the tools branch: https://github.com/flihp/tpm2-tools/tree/extended-sessions-min. Not all tools will build in this last branch but for the test you need only to build:

- tpm2_create
- tpm2_flushcontext
- tpm2_load
- tpm2_policypcr
- tpm2_policyrestart
- tpm2_unseal
- tpm2_clear
- tpm2_createprimary
- tpm2_pcrlist
- tpm2_startauthsession

**Comment by flihp** [comment]
all fixes were merged about a week ago, closing
