### ISSUE TITLE
TCTI & config encoding

### ISSUE THREAD

**Issue by flihp** [tpm2-software/tpm2-abrmd#321]
The tools and now tabrmd are now using the dynamic TCTI loading & initialization stuff. The last place to thing we need to align is how we have the user pass in the TCTI data. This issue will collect data on the current approaches (documented in the respective projects currently) and sort through our options.

**Comment by flihp** [comment]
this discussion started in PR #320

**Comment by williamcroberts** [comment]
Picking up:
```
--tcti=tcti://device/?file=/dev/tpm0
--tcti=tcti://abrmd/?bus_type=session&bus_name=foo.bar
```
Looking at your example, it has the tcti as the URL, I was thinking more along the lines of using existing URL schemes. IIRC dbus has one, not sure of it's format though.

We could map a default scheme to a tcti.

```
--tcti=file:///dev/tpm0
--tcti=dbus://session/bus_name=foo.bar
```
Then for dynamic or explicit coercion (ie ignore scheme to tcti map):
```
--tcti=/path/to/my/lib:file:///foo/bar
```
I'm just spit balling here. People may gawk and the amount of characters and complexity
required to spin up a tcti.

@martinezjavier always interested in any thoughts you have on this.

**Comment by flihp** [comment]
I'm not sure that anything we've come up with is better than the way the tools is doing this. Changes to the tabrmd to go this way are very small since it's just concatenating two string options into one and separating them with a `:`. Good enough. Should be fixed by #330

**Comment by williamcroberts** [comment]
@flihp close me

**Comment by martinezjavier** [comment]
> @martinezjavier always interested in any thoughts you have on this.

@flihp Sorry I missed that you mentioned me... I've been very busy with other internal projects and there are so many moving parts around the TCTI stuff, so I couldn't get a lot of attention to the tpm2-* project. I should have more time in the following weeks though, I hope to use it to catch up.

Now that #330 is merged this issue should be closed though, right?

**Comment by flihp** [comment]
yup yup, doing janitorial work now in preparation for 1.3.0 RC
