### ISSUE TITLE
Make a new 1.x release that contains a correct SELinux policy module

### ISSUE THREAD

**Issue by martinezjavier** [tpm2-software/tpm2-abrmd#325]
Commit d2d1d0787ef2 ("[SELinux] Remove gen_require part from tpm-abrmd2 policy.") fixed the SELinux policy module so it can be independently installed in systems using SELinux (i.e: Fedora).

**Comment by martinezjavier** [comment]
@flihp it seems I don't have permissions to neither assign the issue to you nor set a milestone / deadline.

The new Fedora release is 28 and it will be branched out from Rawhide (development) on February 20 (https://fedoraproject.org/wiki/Releases/28/Schedule). It would be nice to have the release by 18th so I've a couple of days so people can review and accept the package updates.

But on the other hand is not critical to have the latest 1.x version, the current tpm2-abrmd package in Fedora is 1.1.0 (before needing a SELinux policy) which is still compatible with tpm2-tools 3.0.3 and tpm2-tss 1.3.0 that will be in F28. So it won't be an issue to not have a new release, tt's just nice to have the latest version.

**Comment by flihp** [comment]
hmmmm these github permissions are new to me. Sorry for the confusion there.  I'll get all this set up. Having a week to turn the release crank is plenty of time. Thanks!
