### ISSUE TITLE
The udev rule for the TPM2 character device needs improvement

### ISSUE THREAD

**Issue by martinezjavier** [tpm2-software/tpm2-abrmd#334]
Currently the tpm2-abrmd installs [the following udev rule](https://github.com/tpm2-software/tpm2-abrmd/blob/master/dist/tpm-udev.rules):

```
# tpm2-abrmd should be run as unprivileged tss user
KERNEL=="tpm[0-9]*", MODE="0600", OWNER="tss", GROUP="tss"
```

The rule is missing several things:
* It only takes into account `/dev/tpm[0-9]*` devices but no `/dev/tpmrm[0-9]*` devices.
* It sets the permission modes to `rw` for the `tss` user but no for the `tss` group (what's the point of setting to that group then?).
* It's installed by the `tpm2-abrmd`, but what if a user wants to use without the user-space resource manager?

So I think we should change the permission bits to `0660`, that way users that belong to the `tss` group will also be able to access the device. And that we should move the udev rule to the tpm2-tss package since that's where I think it should belong.

@flihp @williamcroberts @tstruk opinions?

**Comment by martinezjavier** [comment]
I've fixed the two first issues, I still think we should move this to tpm2-tss though since users may either use the tpm2-tools an the device TCTI or just the sapi and tcti libraries directly.

**Comment by williamcroberts** [comment]
@martinezjavier I think SAPI would be the place for it, since it's the lowest component in the stack that uses TPM and we're all dependent on it.

**Comment by martinezjavier** [comment]
@williamcroberts yes, that's why I say that we should move to the tpm2-tss project. It doesn't really belong in the tpm2-abrmd project.

**Comment by tstruk** [comment]
@martinezjavier I agree, this should be moved to tpm2-tss

**Comment by flihp** [comment]
Just merged #335 to get this into the next 1.x release. No objections to moving this into repo with TSS2 libraries once 2.0 release pressure lets up. I expect a 2.1 will happen pretty quickly.

**Comment by martinezjavier** [comment]
@flihp aweome, thanks. I don't really mind keeping it in tpm2-abrmd, I was mostly thinking in long term to find a more suitable place for it.

**Comment by martinezjavier** [comment]
@flihp this can be closed now. It's annoying that Github only closes it automatically when commits are merged into the master branch.
