### ISSUE TITLE
How to specify TCTI config string when running as a service?

### ISSUE THREAD

**Issue by svenschwermer** [tpm2-software/tpm2-abrmd#373]
When tpm2-abrmd runs as a service, how can we specify the TCTI configuration (what's passed via `--tcti`) without modifying the tpm2-abrmd.service file in the `ExecStart` line? I have seen the possibility of specifying a environment config file (`EnvironmentFile=-/etc/default/tpm2-abrmd`), but I couldn't find a way to specify the TCTI config via an environment variable. Who knows more?

**Comment by svenschwermer** [comment]
I just found this man page: https://github.com/tpm2-software/tpm2-tools/blob/master/man/common/tcti.md
Is `TPM2TOOLS_TCTI_NAME` the environment variable I am looking for?

**Comment by flihp** [comment]
If you're looking to do something beyond the default you'll have to manually edit the systemd unit file. I'm not very experienced with systemd but a quick google search turned up something they call `instances` which looks like it might be useful for something like this.

**Comment by flihp** [comment]
forgot the link in my last comment: http://0pointer.de/blog/projects/instances.html
