### ISSUE TITLE
Startup error with SLB9670 device

### ISSUE THREAD

**Issue by svenschwermer** [tpm2-software/tpm2-abrmd#394]
I am using the current master branches from tpm2-tss and tpm2-abrmd. I am using a 4.9.80 kernel (Raspberry Pi fork) with an Infineon SLB9670 hardware TPM 2.0. When I start up tpm2-abrmd, I get the following error:
```
** (tpm2-abrmd:10483): WARNING **: Tss2_Sys_Startup returned unexpected RC: 0x144

** (tpm2-abrmd:10483): WARNING **: access_broker_sent_tpm_startup failed: 0x144
```
This error code corresponds to `the value of authorizationSize is out of range or the number of octets in the Authorization Area is greater than required`. Using Infineon's [eltt2](https://github.com/Infineon/eltt2), I am able to get the TPM's capabilities, so the communication seems to work.

**Comment by svenschwermer** [comment]
The same thing happens with a 4.14.27 kernel.

**Comment by PeterHuewe** [comment]
Hi svenschwermer,
what is the firmware version of the TPM according to eltt2?
What happens if you send another startup via ELTT, do you also get the 0x144?
I will try to reproduce it.
Thanks Peter
(Infineon)

**Comment by svenschwermer** [comment]
```
$ sudo -u tss ./eltt2 -g


TPM capability information of fixed properties:
=========================================================
TPM_PT_FAMILY_INDICATOR:        2.0
TPM_PT_LEVEL:                   0
TPM_PT_REVISION:                116
TPM_PT_DAY_OF_YEAR:             15
TPM_PT_YEAR:                    2016
TPM_PT_MANUFACTURER:            IFX
TPM_PT_VENDOR_STRING:           SLB9670
TPM_PT_VENDOR_TPM_TYPE:         0
TPM_PT_FIRMWARE_VERSION:        7.62.3126.0

TPM_PT_MEMORY:
=========================================================
Shared RAM:                     0 CLEAR
Shared NV:                      1 SET
Object Copied To Ram:           1 SET

TPM_PT_PERMANENT:
=========================================================
Owner Auth Set:                 0 CLEAR
Sendorsement Auth Set:          0 CLEAR
Lockout Auth Set:               0 CLEAR
Disable Clear:                  0 CLEAR
In Lockout:                     0 CLEAR
TPM Generated EPS:              0 CLEAR
```
The startup command doesn't seem to work, but I'm getting a different error code:
```
$ sudo -u tss ./eltt2 -u

TPM Error 0x00000100: TPM not initialized.
```

**Comment by PeterHuewe** [comment]
Thanks for the fast reply.
TPM Error 0x00000100: TPM not initialized. 
is exactly what I was expecting.

**Comment by svenschwermer** [comment]
This happens even when I disable the abrmd service, power-cycle and try to run `./eltt2 -u`. Is that expected? Similarly, when power-cycling the device with abrmd enabled, abrmd doesn't start up properly with the error code mentioned above (0x144).

**Comment by svenschwermer** [comment]
The error doesn't exist in the 1.x versions of tss and abrmd (and 3.x of tools), so I guess this is an issue on master of tss. Perhaps I should file an issue there.
