### ISSUE TITLE
Add scan-build to Travis builds

### ISSUE THREAD

**Issue by danintel** [tpm2-software/tpm2-abrmd#428]
Add the clang scan-build static coded analysis to Travis builds.

I will work on this issue.

**Comment by flihp** [comment]
re-opening this given the findings from my work on #440, the issue filed in response #447, and the current PR to revert PR #429

**Comment by flihp** [comment]
branch with the CFLAGS thing fixed is here: https://github.com/flihp/tpm2-abrmd/tree/scan-build. `scan-build` now identifies 19 issues.
