### ISSUE TITLE
test/integration failed with hwtpm

### ISSUE THREAD

**Issue by gitfineon** [tpm2-software/tpm2-abrmd#434]
The output told me I shall report this :grin: 

Build on HiKey620 Development Board with Kernel 4.12 (aarch64) under Debian GNU/Linux buster/sid
``` bash
cd ../tpm2-abrmd/
./bootstrap
./configure --enable-unit --enable-test-hwtpm
```
> The integration tests are executed on a real TPM2 hardware through running make check. Note that it requires the elevated privilege (possibly root access depending on your platforms configuration) to launch tpm2-abrmd and to access /dev/tpm0. WARNING: If this test suite is executed against a TPM2 it may result in the TPM2 device being damaged or destroyed. You have been warned ... again.

Yes, I've read the warning!

Btw: [Documentation](https://github.com/tpm2-software/tpm2-abrmd/blob/master/INSTALL.md#run-integration-tests-with-hardware-tpm2---test-hwtpm) states the `test-hwtpm` flag wrong. Can someone append it to his PR?

First try was done without root priviledge:
```
dbus-launch make check
```
Compilation finishes but all tests in the integration folder fail. Did I miss any flags at configure?
``` diff
...
make  check-TESTS
make[2]: Entering directory '/home/linaro/tpm2-abrmd'
make[3]: Entering directory '/home/linaro/tpm2-abrmd'
-FAIL: test/integration/auth-session-max.int
-FAIL: test/integration/auth-session-start-flush.int
-FAIL: test/integration/auth-session-start-save.int
-FAIL: test/integration/auth-session-start-save-load.int
-FAIL: test/integration/create-keys.int
-FAIL: test/integration/get-capability-handles-transient.int
-FAIL: test/integration/manage-transient-keys.int
-FAIL: test/integration/session-load-from-closed-connection.int
-FAIL: test/integration/session-load-from-closed-connections-lru.int
-FAIL: test/integration/session-load-from-open-connection.int
+XFAIL: test/integration/start-auth-session.int
-FAIL: test/integration/tcti-cancel.int
-FAIL: test/integration/tcti-connections-max.int
-FAIL: test/integration/tcti-double-finalize.int
-FAIL: test/integration/tcti-set-locality.int
-FAIL: test/integration/hash-sequence.int
-FAIL: test/integration/not-enough-handles-for-command.int
-FAIL: test/integration/password-authorization.int
-FAIL: test/integration/tpm2-command-flush-no-handle.int
-FAIL: test/integration/util-buf-max-upper-bound.int
+PASS: test/access-broker_unit
+PASS: test/command-attrs_unit
+PASS: test/connection_unit
+PASS: test/connection-manager_unit
+PASS: test/logging_unit
+PASS: test/message-queue_unit
+PASS: test/resource-manager_unit
+PASS: test/response-sink_unit
+PASS: test/command-source_unit
+PASS: test/handle-map-entry_unit
+PASS: test/handle-map_unit
+PASS: test/ipc-frontend_unit
+PASS: test/ipc-frontend-dbus_unit
+PASS: test/random_unit
+PASS: test/session-entry_unit
+PASS: test/test-skeleton_unit
+PASS: test/tcti-dynamic_unit
+PASS: test/tcti-echo_unit
+PASS: test/tcti-util_unit
+PASS: test/thread_unit
+PASS: test/tpm2-command_unit
+PASS: test/tpm2-response_unit
+PASS: test/tss2-tcti-tabrmd_unit
+PASS: test/tss2-tcti-echo_unit
+PASS: test/util_unit
============================================================================
Testsuite summary for tpm2-abrmd 1.3.1-149-gf317228
============================================================================
# TOTAL: 45
+# PASS:  25
# SKIP:  0
+# XFAIL: 1
-# FAIL:  19
# XPASS: 0
# ERROR: 0
============================================================================
See ./test-suite.log
Please report to https://github.com/01org/tpm2-abrmd/issues
============================================================================
Makefile:3346: recipe for target 'test-suite.log' failed
make[3]: *** [test-suite.log] Error 1
make[3]: Leaving directory '/home/linaro/tpm2-abrmd'
Makefile:3452: recipe for target 'check-TESTS' failed
make[2]: *** [check-TESTS] Error 2
make[2]: Leaving directory '/home/linaro/tpm2-abrmd'
Makefile:3826: recipe for target 'check-am' failed
make[1]: *** [check-am] Error 2
make[1]: Leaving directory '/home/linaro/tpm2-abrmd'
Makefile:3829: recipe for target 'check' failed
make: *** [check] Error 2
linaro@linaro-developer:~/tpm2-abrmd$ 
```

Logfile: [180425-1700_tpm2-abrmd_test-suite.log](https://github.com/tpm2-software/tpm2-abrmd/files/1947574/180425-1700_tpm2-abrmd_test-suite.log)

A Second try have been executed with elevated privilege
```
sudo su
dbus-launch make check
```
No difference in the result, only multiple times slower!
I traced the spi interface, but nothing happens ... 

Used current master of the tpm2-tss (tpm2-software/tpm2-tools@e394cffe3add7874299b9571e0b5140b4dc51dfe)
``` git
commit e394cffe3add7874299b9571e0b5140b4dc51dfe (HEAD -> master, origin/master, origin/HEAD)
Author: Philip Tricca <philip.b.tricca@intel.com>
Date:   Wed Apr 18 08:36:06 2018 -0700
```
and current master of tpm2-abrmd (f3172288fa95998255f79ab219125697d7d95025)
```
commit f3172288fa95998255f79ab219125697d7d95025 (HEAD -> master, origin/master, origin/HEAD)
Author: Philip Tricca <philip.b.tricca@intel.com>
Date:   Tue Apr 24 12:25:28 2018 -0700
```

**Comment by flihp** [comment]
Thanks for the detailed report @gitfineon. That first log file you posted has a bunch of output indicating:
```
device TCTI requires root privileges
```
You then ran the test harness again as root and you state the result is the same but I wonder if the output in the log is changed. Can you please post the log file from your second test run (as root)?

**Comment by flihp** [comment]
I just went through a test run against some "real" tpm hardware (found a buggy test case in the process so that was useful). I managed to get this working following your general setup just on a different board (MinnowboardMax with 32bit firmware & OS) since I don't have a HiKey620. The only hint from your data is that the second test run was a lot slower which indicates that the test executable are trying to connect to the tabrmd and timing out. Hopefully there will be something more useful in your log once you post it.

**Comment by gitfineon** [comment]
Thank you @flihp for answering and patching that fast. Test is running again ... 

Yesterday the observation with root privileges was
> No difference in the result, only multiple times slower!
> I traced the spi interface, but nothing happens ...

And I missed to read to read the logfile carefully

Today it seems to be multiple times slower than yesterday, but there is communication happening on the spi bus. I'll paste the logfile(s) when it has finished ....  :sleeping:
At first I canceled the tests because nothing was happening for some minutes, then I cleaned and rebuild with option -j4 and let it run in the background (longer) ... this time four results are printed simultaneously, hopefully the test are not executed simultaneously

**Comment by gitfineon** [comment]
Still running, but I can paste the detailed logs of the tests itself, e.g:
* auth-session-max.int (first test)
  - [180426-1045_auth-session-max.int_tabrmd.log](https://github.com/tpm2-software/tpm2-abrmd/files/1950619/180426-1045_auth-session-max.int_tabrmd.log)
  - [180426-1050_auth-session-max.log](https://github.com/tpm2-software/tpm2-abrmd/files/1950608/180426-1050_auth-session-max.log)

* auth-session-start-save-load.int (second test, simultaneously)
  - [180426-1045_auth-session-start-save-load.int_tabrmd.log](https://github.com/tpm2-software/tpm2-abrmd/files/1950621/180426-1045_auth-session-start-save-load.int_tabrmd.log)
  - [180426-1050_auth-session-start-save-load.log](https://github.com/tpm2-software/tpm2-abrmd/files/1950623/180426-1050_auth-session-start-save-load.log)

Test are really executed simultaneously using -j option, which results in device is busy for 3 of 4 tests  :disappointed_relieved:
And the test, which is taking the resource gets an time out:
```
starting daemon: src/tpm2-abrmd
  environment: G_MESSAGES_DEBUG=all
  options: --allow-root --tcti=device:/dev/tpm0
successfully started daemon: src/tpm2-abrmd with PID: 13117
** (process:13152): DEBUG: 10:45:45.186: get_test_opts_from_env: TABRMD_TEST_TCTI_CONF is ""
** (process:13152): DEBUG: 10:45:45.187: get_test_opts_from_env: TABRMD_TEST_TCTI_RETRIES is "10"
** (process:13152): DEBUG: 10:45:45.187: tcti_tabrmd_init: with conf: ""
** (process:13152): DEBUG: 10:45:45.187: parse_key_value_string: kv_str: "", callback: 0xffff79b0fe10, user_data: 0xffffd89f8768

** (process:13152): CRITICAL **: 10:46:10.199: failed to allocate dbus proxy object: Error calling StartServiceByName for com.intel.tss2.Tabrmd: GDBus.Error:org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'com.intel.tss2.Tabrmd': timed out (service_start_timeout=25000ms)
Failed to initialize tabrmd TCTI context: 0xa0008
** (process:13152): DEBUG: 10:46:10.200: sapi_init_from_opts: tcti_ctx returned NULL on try: 0
** (process:13152): DEBUG: 10:46:11.200: tcti_tabrmd_init: with conf: ""
** (process:13152): DEBUG: 10:46:11.200: parse_key_value_string: kv_str: "", callback: 0xffff79b0fe10, user_data: 0xffffd89f8768

** (process:13152): CRITICAL **: 10:46:36.211: failed to allocate dbus proxy object: Error calling StartServiceByName for com.intel.tss2.Tabrmd: GDBus.Error:org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'com.intel.tss2.Tabrmd': timed out (service_start_timeout=25000ms)
Failed to initialize tabrmd TCTI context: 0xa0008
** (process:13152): DEBUG: 10:46:36.212: sapi_init_from_opts: tcti_ctx returned NULL on try: 1
...
```

Do you need another log? Do I have to set a dbus option for configure?

As I said, I was able to trace some communication happening ... I guess configuration is not the problem?

I will pull your changes an retry after lunch.

**Comment by gitfineon** [comment]
Ok, tests are running for ages because of the timeout and retry stuff ... 

```
root@linaro-developer:/home/linaro/tpm2-abrmd# dbus-launch make check | ts -s
00:00:00 make  check-am
00:00:01 make[1]: Entering directory '/home/linaro/tpm2-abrmd'
...
00:01:54 make[2]: Leaving directory '/home/linaro/tpm2-abrmd'
00:01:54 make  check-TESTS
00:01:54 make[2]: Entering directory '/home/linaro/tpm2-abrmd'
00:01:55 make[3]: Entering directory '/home/linaro/tpm2-abrmd'
00:06:17 FAIL: test/integration/auth-session-max.int
```
about an hour later ... still hangs here!

1. `auth-session-max.int` (first test)
   - [180426-1426_auth-session-max.int_tabrmd.log](https://github.com/tpm2-software/tpm2-abrmd/files/1951299/180426-1426_auth-session-max.int_tabrmd.log)
   - [180426-1430_auth-session-max.log](https://github.com/tpm2-software/tpm2-abrmd/files/1951304/180426-1430_auth-session-max.log)

   something is happening in the end of `auth-session-max` or at the beginning of `auth-session-start-save-load`
   - [180426-1430_Transceive.log](https://github.com/tpm2-software/tpm2-abrmd/files/1951371/180426-1430_Transceive.log) (tab-separated values)

2. `auth-session-start-save-load.int` (second test, simultaneously)
   - [180426-1430_auth-session-start-flush.int_tabrmd.log](https://github.com/tpm2-software/tpm2-abrmd/files/1951376/180426-1430_auth-session-start-flush.int_tabrmd.log)
   - [180426-1435_auth-session-start-flush.log](https://github.com/tpm2-software/tpm2-abrmd/files/1951377/180426-1435_auth-session-start-flush.log)

``` bash
sudo systemctl status tpm2-abrmd.service

● tpm2-abrmd.service - TPM2 Access Broker and Resource Management Daemon
   Loaded: loaded (/usr/local/lib/systemd/system/tpm2-abrmd.service; disabled; vendor preset: enabled)
   Active: activating (start) since Thu 2018-04-26 15:13:40 UTC; 7ms ago
 Main PID: 6707 ((m2-abrmd))
    Tasks: 0 (limit: 2177)
   Memory: 0B
   CGroup: /system.slice/tpm2-abrmd.service
           └─6707 [(m2-abrmd)]

Apr 26 15:13:40 linaro-developer systemd[1]: Starting TPM2 Access Broker and Resource Management Daemon...
Apr 26 15:13:40 linaro-developer systemd[6707]: tpm2-abrmd.service: Failed to determine user credentials: No such process
Apr 26 15:13:40 linaro-developer systemd[6707]: tpm2-abrmd.service: Failed at step USER spawning /usr/local/sbin/tpm2-abrmd: No such process
Apr 26 15:13:40 linaro-developer systemd[1]: tpm2-abrmd.service: Main process exited, code=exited, status=217/USER
Apr 26 15:13:40 linaro-developer systemd[1]: tpm2-abrmd.service: Failed with result 'exit-code'.
```
auto-restart the deamon is happening all the time ... every 5 seconds I guess!
``` bash
sudo systemctl status tpm2-abrmd.service
● tpm2-abrmd.service - TPM2 Access Broker and Resource Management Daemon
   Loaded: loaded (/usr/local/lib/systemd/system/tpm2-abrmd.service; disabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2018-04-26 15:34:09 UTC; 3s ago
  Process: 6963 ExecStart=/usr/local/sbin/tpm2-abrmd (code=exited, status=217/USER)
 Main PID: 6963 (code=exited, status=217/USER)
```

**Comment by gitfineon** [comment]
I've read this post of @idesai: https://github.com/tpm2-software/tpm2-abrmd/issues/92#issuecomment-310176492
But @martinezjavier has reverted the udevrulesdir option: https://github.com/tpm2-software/tpm2-abrmd/commit/c903f42539452b7d3425699ee62d87c1448743f2 3 days ago
There is no user `tss` registered on my system and no directory `/var/lib/tpm`, but theres no documentation that it is my job to create them, right?

btw: tested with dbuspolicydir
``` bash
./configure --enable-unit --enable-test-hwtpm --with-dbuspolicydir=/etc/dbus-1/system.d
make -j4
make install
dbus-launch make check | ts -s
```
```
00:01:52 make  check-TESTS
00:01:52 make[2]: Entering directory '/home/linaro/tpm2-abrmd'
00:01:53 make[3]: Entering directory '/home/linaro/tpm2-abrmd'
00:06:15 FAIL: test/integration/auth-session-max.int
00:10:38 FAIL: test/integration/auth-session-start-flush.int
00:15:00 FAIL: test/integration/auth-session-start-save.int
00:19:22 FAIL: test/integration/auth-session-start-save-load.int
```
Error is the same for all:
```
** (process:17356): CRITICAL **: 16:02:54.009: failed to allocate dbus proxy object: Error calling StartServiceByName for com.intel.tss2.Tabrmd: GDBus.Error:org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'com.intel.tss2.Tabrmd': timed out (service_start_timeout=25000ms)
Failed to initialize tabrmd TCTI context: 0xa0008
```

Try to pull tpm2-tss master again and if that doesn't help I have to focus on old released version.

**Comment by gitfineon** [comment]
> There is no user tss registered on my system [...], but theres no documentation that it is my job to create them, right?

Sorry, seems I've followed an older installation guide. But it is not necessary, right?

Did update https://github.com/tpm2-software/tpm2-tss/commit/5a7c4f45d13417de2a39f359b6468e0c26d55355 to latest master and reinstalled, following the [INSTALL.md](https://github.com/tpm2-software/tpm2-tss/blob/0075f88466d791b2b58c60adafed87ec814441df/INSTALL.md) 
``` bash
cd /home/linaro/tpm2-tss
./configure --enable-unit --with-udevrulesdir=/etc/udev/rules.d
make -j4
make install
ls -lah /etc/udev/rules.d/ # found the rule!
sudo udevadm control --reload-rules && sudo udevadm trigger
ldconfig
```
Followed the updated [INSTALL.md](https://github.com/tpm2-software/tpm2-abrmd/blob/de6ccda877d2501af3b3b84a751e351340b8166e/INSTALL.md) of tpm2-abrmd https://github.com/tpm2-software/tpm2-abrmd/commit/de6ccda877d2501af3b3b84a751e351340b8166e
```
cd ../tpm2-abrmd/
sudo useradd --system --user-group tss
./bootstrap
./configure --enable-unit --enable-test-hwtpm
make -j4
sudo make install
ldconfig
pkill -HUP dbus-daemon
systemctl daemon-reload
dbus-send --system --dest=org.freedesktop.DBus --type=method_call --print-reply /org/freedesktop/DBus org.freedesktop.DBus.ListNames
```
```
method return time=1524762193.706944 sender=org.freedesktop.DBus -> destination=:1.1636 serial=3 reply_serial=2
   array [
      string "org.freedesktop.DBus"
      string "org.freedesktop.login1"
      string ":1.8"
      string "org.freedesktop.systemd1"
      string "org.freedesktop.PolicyKit1"
      string ":1.10"
      string ":1.77"
      string "org.freedesktop.NetworkManager"
      string ":1.0"
      string ":1.1"
      string ":1.2"
      string ":1.3"
      string "fi.epitest.hostap.WPASupplicant"
      string "fi.w1.wpa_supplicant1"
      string ":1.1636"
      string ":1.6"
   ]
```
The string `"com.intel.tss2.Tabrmd"` you have stated is missing!

**Comment by gitfineon** [comment]
Added `--with-systemdsystemunitdir=/usr/lib/systemd/system --libdir=/usr/lib64 --prefix=/usr` as mentioned in this PR https://github.com/tpm2-software/tpm2-tools/pull/978, but `com.intel.tss2.Tabrmd` still not registered in dbus.

**Comment by martinezjavier** [comment]
@gitfineon ah, I see that Debian. Also, could you try running it from the shell just to make sure that it works?
```
sudo -u tss ./src/tpm2-abrmd
```

If that fails, you can run it with `G_MESSAGES_DEBUG=all` to see the debug messages.

**Comment by flihp** [comment]
When the test harness is used to run tests against the "real" TPM the whole `tss` user, udev and dbus config stuff doesn't really apply. When you're setting up your system to start the daemon when it boots then yeah you should set all that up but when you run the the test harness against your TPM hardware the current setup assumes that you run it as root so permissions don't apply.

All that said the related docs are pretty sparse (I didn't write them). No better time to fill them in though. I'll keep doing that today and hopefully I'll end up answering some of the riddles in this thread along the way :grinning:

**Comment by flihp** [comment]
https://github.com/tpm2-software/tpm2-abrmd/pull/438

**Comment by gitfineon** [comment]
Ok weird, I don't know why it passed most of the tests this time. I'll tell you my steps:

- My Board does not have a RTC battery for date/time so I did it manually to avoid build warnings
   ``` bash
   date +%Y%m%d -s "20180502"
   date +%T -s "11:00:00"
   ```
- Today I decided to use systemd-timesyncd to automatically sync date/time
   ``` bash
   timedatectl set-ntp false
   vim /etc/systemd/timesyncd.conf
   # enter NTP=[server]
   timedatectl list-timezones
   timedatectl set-timezone Europe/Berlin
   systemctl restart systemd-networkd
   systemctl restart systemd-timesyncd
   timedatectl status
   ```
- Update repo and rebuild
   ``` bash
   git pull
   ./bootstrap
   make clean
   ./configure --enable-test-hwtpm
   make -j4
   make check TESTS=test/integration/auth-session-start-flush.int
   # PASS:  1
   ```
Well, the single test passed, why not test the complete test suite with `make check`:
``` diff
+PASS: test/integration/auth-session-max.int
+PASS: test/integration/auth-session-start-flush.int
+PASS: test/integration/auth-session-start-save.int
+PASS: test/integration/auth-session-start-save-load.int
+PASS: test/integration/create-keys.int
+PASS: test/integration/get-capability-handles-transient.int
+PASS: test/integration/manage-transient-keys.int
+PASS: test/integration/session-load-from-closed-connection.int
+PASS: test/integration/session-load-from-closed-connections-lru.int
+PASS: test/integration/session-load-from-open-connection.int
-XFAIL: test/integration/start-auth-session.int
+PASS: test/integration/tcti-cancel.int
+PASS: test/integration/tcti-connections-max.int
+PASS: test/integration/tcti-double-finalize.int
+PASS: test/integration/tcti-set-locality.int
+PASS: test/integration/hash-sequence.int
+PASS: test/integration/not-enough-handles-for-command.int
+PASS: test/integration/password-authorization.int
+PASS: test/integration/tpm2-command-flush-no-handle.int
+PASS: test/integration/util-buf-max-upper-bound.int
+PASS: test/integration/tcti-connect-multiple.int
============================================================================
Testsuite summary for tpm2-abrmd 1.3.1-155-g0ba8be3
============================================================================
 # TOTAL: 21
+# PASS:  20
 # SKIP:  0
-# XFAIL: 1
 # FAIL:  0
 # XPASS: 0
 # ERROR: 0
============================================================================

```
Log files:
[180502-1154_config.log](https://github.com/tpm2-software/tpm2-abrmd/files/1967320/180502-1154_config.log)
[180502-1205_start-auth-session.int_tabrmd.log](https://github.com/tpm2-software/tpm2-abrmd/files/1967321/180502-1205_start-auth-session.int_tabrmd.log)
[180502-1205_start-auth-session.log](https://github.com/tpm2-software/tpm2-abrmd/files/1967322/180502-1205_start-auth-session.log)
[180502-1205_test-suite.log](https://github.com/tpm2-software/tpm2-abrmd/files/1967323/180502-1205_test-suite.log)

**Comment by flihp** [comment]
Apologies for the slow reply @gitfineon. No clue why your current test runs are passing but we got some good updates to the documentation and procedures resolved in the process so I'm happy. That last test failure is expected (XFAIL) so despite the mystery I'm going to close this issue since it seems to be resolved.

**Comment by gitfineon** [comment]
Thank you very much @flihp . Good job done for the documentation.
Can you tell me, why start-auth-session.int is expected to fail?
