### ISSUE TITLE
TEMP_FAILURE_RETRY is specific to the GNU C Library

### ISSUE THREAD

**Issue by safayetahmedatge** [tpm2-software/tpm2-abrmd#475]
https://github.com/tpm2-software/tpm2-abrmd/blob/c90cd599bbde05514a6396ad25c47aec74bbd70a/src/tcti-tabrmd.c#L168

This is problematic on platforms that use a non-GNU C library like musl libc in Alpine containers. The musl libc headers don't implement TEMP_FAILURE_RETRY.

Other projects that see similar issues address it with preprocessor directives similar to the following:
```
#ifndef TEMP_FAILURE_RETRY
#define TEMP_FAILURE_RETRY(expression) \
...
```
We could do the same in 'src/util.h'. My preference would be to just copy the implementation from an existing project but I am unsure of the licensing restrictions. Can tpm2-abrmd include Apache licensed code like the following?

https://android.googlesource.com/platform/system/core/+/master/base/include/android-base/macros.h#26

**Comment by flihp** [comment]
We have an implementation of this paradigm in tpm2-tss for handling retries on Windows and Linux. Should be easy enough to just use that code.

**Comment by safayetahmedatge** [comment]
Thanks @flihp. Will look into it.
