### ISSUE TITLE
tpm2-abrmd.service is getting killed

### ISSUE THREAD

**Issue by dassanjib** [tpm2-software/tpm2-abrmd#479]
Hi @flihp,

I went through this entire email/message chain (https://github.com/tpm2-software/tpm2-abrmd/issues/32) & tried all steps recommended there. Unfortunately I still find issue in running tpm2_abrmd daemon [tpm_server is running successfully]. My tpm2-abrmd.service is getting killed.

Took this tar ball
https://github.com/tpm2-software/tpm2-abrmd/releases/tag/2.0.0
tpm2-abrmd-2.0.0.tar.gz

./configure
make
make install

[tpm2-abrmd-2.0.0]ls /etc/udev/rules.d/
tpm-udev.rules

[tpm2-abrmd-2.0.0]sudo systemctl enable tpm2-abrmd.service
[tpm2-abrmd-2.0.0]
[tpm2-abrmd-2.0.0]
[tpm2-abrmd-2.0.0]sudo systemctl status tpm2-abrmd.service
● tpm2-abrmd.service - TPM2 Access Broker and Resource Management Daemon
Loaded: loaded (/usr/local/lib/systemd/system/tpm2-abrmd.service; enabled; ve
Active: activating (auto-restart) (Result: signal) since Tue 2018-06-26 12:17
Process: 20023 ExecStart=/usr/local/sbin/tpm2-abrmd (code=killed, signal=TRAP)
Main PID: 20023 (code=killed, signal=TRAP)

Jun 26 12:17:20 ubuntu systemd[1]: tpm2-abrmd.service: Main process exited, code
Jun 26 12:17:20 ubuntu systemd[1]: tpm2-abrmd.service: Unit entered failed state
Jun 26 12:17:20 ubuntu systemd[1]: tpm2-abrmd.service: Failed with result 'signa
lines 1-9/9 (END)[ 9049.101241] tpm tpm0: Operation Timed out

[tpm2-abrmd-2.0.0]cat /usr/local/lib/udev/rules.d/tpm-udev.rules
tpm devices can only be accessed by the tss user but the tss
group members can access tpmrm devices

KERNEL=="tpm[0-9]", MODE="0660", OWNER="tss"
KERNEL=="tpmrm[0-9]", MODE="0660", OWNER="tss", GROUP="tss"

[tpm2-abrmd-2.0.0]ls -l /dev/tpm0
crw------- 1 tss tss 10, 224 Jun 26 09:46 /dev/tpm0

[tpm2-abrmd-2.0.0]journalctl -xe
-- Unit tpm2-abrmd.service has finished shutting down.
Jun 26 12:29:03 ubuntu systemd[1]: Starting TPM2 Access Broker and Resource Mana
-- Subject: Unit tpm2-abrmd.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Unit tpm2-abrmd.service has begun starting up.
Jun 26 12:29:04 ubuntu systemd[1]: Started TPM2 Access Broker and Resource Manag
-- Subject: Unit tpm2-abrmd.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Unit tpm2-abrmd.service has finished starting up.
-- The start-up result is done.
-- The start-up result is done.
Jun 26 12:22:38 ubuntu tpm2-abrmd[21561]: ERROR:tcti:src/util/io.c:81:write_all() failed to write to fd 5: Timer expired
Jun 26 12:22:38 ubuntu kernel: tpm tpm0: Operation Timed out
Jun 26 12:22:38 ubuntu tpm2-abrmd[21561]: ERROR:tcti:src/tss2-tcti/tcti-device.c:85:tcti_device_transmit() wrong number of bytes written. Expected 22, wrote 0.
Jun 26 12:22:38 ubuntu tpm2-abrmd[21561]: ** (tpm2-abrmd:21561): ERROR **: Failed to GetCapability: TPM2_CAP_TPM_PROPERTIES, TPM2_PT_FIXED: 0xa000a
Jun 26 12:22:38 ubuntu kernel: traps: tpm2-abrmd[21562] trap int3 ip:7fce1b7d9a5b sp:7fce19c8bb90 error:0 in libglib-2.0.so.0.4800.2[7fce1b789000+10f000]

[@ubuntu: TSS-TOOL/tpm2-abrmd/tpm2-abrmd] ls -als /sys/class/tpm/tpm0/device/
total 0
0 drwxr-xr-x 5 root root 0 Jun 26 10:27 .
0 drwxr-xr-x 19 root root 0 Jun 26 09:46 ..
0 lrwxrwxrwx 1 root root 0 Jun 26 10:27 driver -> ../../../bus/platform/drivers/tpm_tis
0 -rw-r--r-- 1 root root 4096 Jun 26 10:27 driver_override
0 -r--r--r-- 1 root root 4096 Jun 26 10:27 modalias
0 drwxr-xr-x 2 root root 0 Jun 26 10:27 power
0 lrwxrwxrwx 1 root root 0 Jun 26 09:46 subsystem -> ../../../bus/platform
0 drwxr-xr-x 3 root root 0 Jun 26 09:46 tpm
0 drwxr-xr-x 3 root root 0 Jun 26 09:46 tpmrm
0 -rw-r--r-- 1 root root 4096 Jun 26 09:46 uevent

[@ubuntu: TSS-TOOL/tpm2-abrmd/tpm2-abrmd] dmesg | grep -i tpm_tis
[ 3.079658] tpm_tis tpm_tis: 2.0 TPM (device-id 0x3205, rev-id 1)
[tpm2-abrmd-2.0.0]ls /dev/tpm*
/dev/tpm0 /dev/tpmrm0

Not sure if this was seen by others as well, or just happening on my box (kernel-4.14.48) :(
Thanks in advance. You have been always helpful to everyone on any TPM issue.
Appreciate all your help.

Thanks,
Sanjib

**Comment by flihp** [comment]
Your log is showing `ERROR` messages from the underlying tss2 libraries when the `tpm2-abrmd` is running:

>Jun 26 12:22:38 ubuntu tpm2-abrmd[21561]: ERROR:tcti:src/util/io.c:81:write_all() failed to write to fd 5: Timer expired
> Jun 26 12:22:38 ubuntu kernel: tpm tpm0: Operation Timed out
> Jun 26 12:22:38 ubuntu tpm2-abrmd[21561]: ERROR:tcti:src/tss2-tcti/tcti-device.c:85:tcti_device_transmit() wrong number of bytes written. Expected 22, wrote 0.

The one that seems to be most relevant is from your kernel:
> Jun 26 12:22:38 ubuntu kernel: tpm tpm0: Operation Timed out

Are you getting any other relevant errors / messages from the kernel / TPM device driver?

**Comment by dassanjib** [comment]
Hi filhp,

thanks for your reply.
I do see these two additional error messages (not sure if they are relevant here). 
Currently I suppressed them by disabling interrupt.

[    3.534717] genirq: Flags mismatch irq 9. 00000000 (tpm0) vs. 00000080 (acpi)
[    3.542078] tpm tpm0: Unable to request irq: 9 for probe

I am trying everything freshly. I shall update the thread with my observation.

Thanks again for your time.

Sanjib

**Comment by dassanjib** [comment]
Hi filhp,

Once again tried (without simulator) & I do see that kernel error (timeout).
Is there any known fix for this timeout issue (transmit fails). I am too doing
google search for this.

tpm2-abrmd is continuously getting restarted. 

tss@ubuntu:/home/tss$ whoami
tss
tss@ubuntu:/home/tss$ sudo systemctl enable tpm2-abrmd.service
tss@ubuntu:/home/tss$ sudo systemctl status tpm2-abrmd.service
● tpm2-abrmd.service - TPM2 Access Broker and Resource Management Daemon
   Loaded: loaded (/usr/local/lib/systemd/system/tpm2-abrmd.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2018-06-29 03:56:10 EDT; 386ms ago
 Main PID: 15695 (tpm2-abrmd)
    Tasks: 6
   Memory: 920.0K
      CPU: 10ms
   CGroup: /system.slice/tpm2-abrmd.service
           └─15695 /usr/local/sbin/tpm2-abrmd

Jun 29 03:56:10 ubuntu systemd[1]: tpm2-abrmd.service: Service hold-off time over, scheduling restart.
Jun 29 03:56:10 ubuntu systemd[1]: Stopped TPM2 Access Broker and Resource Management Daemon.
Jun 29 03:56:10 ubuntu systemd[1]: Starting TPM2 Access Broker and Resource Management Daemon...
Jun 29 03:56:10 ubuntu systemd[1]: Started TPM2 Access Broker and Resource Management Daemon.
tss@ubuntu:/home/tss$ sudo systemctl status tpm2-abrmd.service
● tpm2-abrmd.service - TPM2 Access Broker and Resource Management Daemon
   Loaded: loaded (/usr/local/lib/systemd/system/tpm2-abrmd.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: signal) since Fri 2018-06-29 03:56:11 EDT; 753ms ago
  Process: 15695 ExecStart=/usr/local/sbin/tpm2-abrmd (code=killed, signal=TRAP)
 Main PID: 15695 (code=killed, signal=TRAP)

Jun 29 03:56:11 ubuntu systemd[1]: tpm2-abrmd.service: Main process exited, code=killed, status=5/TRAP
Jun 29 03:56:11 ubuntu systemd[1]: tpm2-abrmd.service: Unit entered failed state.
Jun 29 03:56:11 ubuntu systemd[1]: tpm2-abrmd.service: Failed with result 'signal'.

tss@ubuntu:/home/tss$ journalctl -xe
Jun 29 03:57:00 ubuntu systemd[1]: tpm2-abrmd.service: Service hold-off time over, scheduling restart.
Jun 29 03:57:00 ubuntu systemd[1]: Stopped TPM2 Access Broker and Resource Management Daemon.
-- Subject: Unit tpm2-abrmd.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Unit tpm2-abrmd.service has finished shutting down.
Jun 29 03:57:00 ubuntu systemd[1]: Starting TPM2 Access Broker and Resource Management Daemon...
-- Subject: Unit tpm2-abrmd.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Unit tpm2-abrmd.service has begun starting up.
Jun 29 03:57:00 ubuntu systemd[1]: Started TPM2 Access Broker and Resource Management Daemon.
-- Subject: Unit tpm2-abrmd.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Unit tpm2-abrmd.service has finished starting up.
-- The start-up result is done.
Jun 29 03:57:01 ubuntu tpm2-abrmd[15950]: ERROR:tcti:src/util/io.c:81:write_all() failed to write to fd 5: Timer expired
Jun 29 03:57:01 ubuntu tpm2-abrmd[15950]: ERROR:tcti:src/tss2-tcti/tcti-device.c:85:tcti_device_transmit() wrong number of bytes written. Expected 22, wr
Jun 29 03:57:01 ubuntu kernel: tpm tpm0: Operation Timed out
Jun 29 03:57:01 ubuntu tpm2-abrmd[15950]: ** (tpm2-abrmd:15950): ERROR **: Failed to GetCapability: TPM2_CAP_TPM_PROPERTIES, TPM2_PT_FIXED: 0xa000a
Jun 29 03:57:01 ubuntu kernel: traps: tpm2-abrmd[15951] trap int3 ip:7f418a873a5b sp:7f4189123c10 error:0 in libglib-2.0.so.0.4800.2[7f418a823000+10f000]
Jun 29 03:57:01 ubuntu systemd[1]: tpm2-abrmd.service: Main process exited, code=killed, status=5/TRAP
Jun 29 03:57:01 ubuntu systemd[1]: tpm2-abrmd.service: Unit entered failed state.
Jun 29 03:57:01 ubuntu systemd[1]: tpm2-abrmd.service: Failed with result 'signal'.

[ 3319.245421] tpm tpm0: Operation Timed out
[ 3325.501274] tpm tpm0: Operation Timed out
[ 3331.745480] tpm tpm0: Operation Timed out

tss@ubuntu:/home/tss$ cat /usr/local/lib/udev/rules.d/tpm-udev.rules
#tpm devices can only be accessed by the tss user but the tss
#group members can access tpmrm devices
KERNEL=="tpm[0-9]*", MODE="0660", OWNER="tss"
KERNEL=="tpmrm[0-9]*", MODE="0660", OWNER="tss", GROUP="tss"
tss@ubuntu:/home/tss$ 
tss@ubuntu:/home/tss$ 
tss@ubuntu:/home/tss$ cat /usr/local/lib/systemd/system/tpm2-abrmd.service 
[Unit]
Description=TPM2 Access Broker and Resource Management Daemon

[Service]
Type=dbus
Restart=always
RestartSec=5
EnvironmentFile=/etc/default/tpm2-abrmd
BusName=com.intel.tss2.Tabrmd
StandardOutput=syslog
ExecStart=/usr/local/sbin/tpm2-abrmd
User=tss

[Install]
WantedBy=multi-user.target


I tried to use in-kernel resource manager (/dev/tpmrm0), surprisingly I still
need to provide -T option even though I exported env variables.

Can I use tpmrm0 instead of tpm2-abrmd for basic TPM2.0 command execution?
Infact I tried few commands with tpmrm0, but most of them are not working 

export TPM2TOOLS_TCTI_NAME=device
export TPM2TOOLS_DEVICE_FILE=/dev/tpmrm0
root@ubuntu:/home/cmd_tpm2# sudo -u tss tpm2_pcrlist -T device
sha1:
  0 : 0x75D019EE51A24B3EE85AD4C467C2B28AFF15C6E9
  1 : 0x4A8D5C6B2337EABD51650014BDC3A2249DB9E2AA
  2 : 0xCF4C1FA4308F48C8D368AEE3012164C59DA80834

[cmd_tpm2]tpm2_nvdefine -x 0x1500001 -a 0x40000001 -s 32 -t 0x2000A
[cmd_tpm2]tpm2_nvwrite -x 0x1500001 -a 0x40000001 -F nv.data 
[ 1403.780306] tpm tpm0: Operation Timed out

** (process:2286): WARNING **: Failed to create connection with service: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
ERROR: tcti init allocation routine failed for library: "tabrmd" options: "(null)"
ERROR: Could not load tcti, got: "tabrmd"

root@ubuntu:/home/cmd_tpm2# [  910.387387] tpm tpm0: Operation Timed out

[cmd_tpm2]tpm2_nvread -x 0x1500001 -a 0x40000001 -s 32 -o 0 -T device
ERROR: Failed to read NVRAM area at index 0x1500001
ERROR: Tss2_Sys_NV_Read(0x14A) - tpm:error(2.0): an NV Index is used before being initialized or the state saved by TPM2_Shutdown(STATE) could not be restored
ERROR: Unable to run tpm2_nvread

Thanks,
Sanjib

**Comment by flihp** [comment]
Based on this output @dassanjib it looks like your problem is with your platform. It looks like even with the tpm2-abrmd disabled and your tools configured to communicate with the TPM directly (device TCTI) you're still getting errors directly from the device driver `operation timed out`. I'd recommend finding a different platform and trying to reproduce this behavior. Please re-open this issue if you're able to reproduce this behavior on a different platform.
