### ISSUE TITLE
tcti_util_discover_info(): fallback dlopen() fails

### ISSUE THREAD

**Issue by mgerstner** [tpm2-software/tpm2-abrmd#486]
I just packaged the current releases of tpm2-* and `tpm2-abrmd` fails to start with the following message:

```
failed to dlopen library: libtss2-tcti-device.so
```
In commit d2f0b2d1f0f25f1ef466c88484160ed8edc975f6 you added code and reasoning for why the SONAME should be used during dlopen(). The symlinked .so library is typically only packaged in a -devel package.

The reason for `tpm2-abrmd` failing to start in spite of this commit is that the construction of the fallback library name is wrong. `filename` is set to `libtss2-tcti-device.so`, so the result of the `snprintf` in the fallback code will be `libtss2-tcti-libtss2-tcti-device.so.so.0`. This, naturally, also fails.

The fix is probably to change the filename in `tcti_dynamic_class_init()`, but the whole `PROP_FILE_NAME` won't make sense semantically any more, because it's more like the tcti type instead of a filename that is required here.

Therefore instead of offering a PR, I opened this issue for letting you decide the right approach.

**Comment by mgerstner** [comment]
Actually this code be fixed quite easily after all by doing something like this:

```
Index: tpm2-abrmd-2.0.0/src/tcti-util.c
===================================================================
--- tpm2-abrmd-2.0.0.orig/src/tcti-util.c
+++ tpm2-abrmd-2.0.0/src/tcti-util.c
@@ -53,7 +53,7 @@ tcti_util_discover_info (const char *fil
     if (*tcti_dl_handle == NULL) {
         size = snprintf (filename_xfrm,
                          sizeof (filename_xfrm),
-                         "libtss2-tcti-%s.so.0",
+                         "%s.0",
                          filename);
         if (size >= sizeof (filename_xfrm)) {
             g_critical ("TCTI name truncated in transform.");
```

**Comment by flihp** [comment]
I'm closing this ticket since I think / hope #489 resolves the issue. Please reopen it if I'm mistaken.
