### ISSUE TITLE
"Replace references to drand48_r family of functions for portability" change causes build failure on Ubuntu 16.04

### ISSUE THREAD

**Issue by joshuagl** [tpm2-software/tpm2-abrmd#510]
We do our CI for the tpm2-tools in an Ubuntu 16.04 container. Since #503 our builds of tpm2-abrmd are failing with:

> src/random.c: In function 'random_get_bytes':
> src/random.c:153:9: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
>          *((long int*)&rand[0]) = nrand48 (random->rand_state);
>          ^
> src/random.c: At top level:
> cc1: error: unrecognized command line option '-Wno-cast-function-type' [-Werror]
> cc1: all warnings being treated as errors
> Makefile:2403: recipe for target 'src/src_libutil_la-random.lo' failed
> make[1]: *** [src/src_libutil_la-random.lo] Error 1
> make[1]: *** Waiting for unfinished jobs....
> make[1]: Leaving directory '/workspace/tpm2-abrmd'
> Makefile:1620: recipe for target 'all' failed
> make: *** [all] Error 2

FWIW GCC version is 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9)

**Comment by flihp** [comment]
thanks @joshuagl, the default travis compiler version is older and the type punning check isn't as strict I guess.
