### ISSUE TITLE
TPM 1.2 detection

### ISSUE THREAD

**Issue by flihp** [tpm2-software/tpm2-abrmd#512]
The tabrmd currently does nothing to determine whether the TPM device it's communicating with (or attempting to communicate with) is actually a TPM2. The alternative of course is a TPM1.2 device and when we start sending commands at a TPM1.2 things to south very quickly. I'm not sure the tabrmd code is the right place to do this though as it may be better / more easily done in the device TCTI.

**Comment by tstruk** [comment]
@flihp we do have something in TSS for this. It checks the response if it is a TPM1.2 type.
https://github.com/tpm2-software/tpm2-tss/blob/master/src/tss2-sys/api/Tss2_Sys_Execute.c#L79

**Comment by flihp** [comment]
This was resolved in #669. The tabrmd init thread now returns `EX_UNAVAILABLE` which becomes the daemon exit code when initializing the TPM in the `access_broker_init_tpm` function fails. Like @tstruk points out above, libtss2-sys will report a general error when it receives a response buffer from a 1.2 TPM device. All errors from this function are treated as unrecoverable and will prevent systemd from attempting to restart the daemon.
