### ISSUE TITLE
default behavior of the --enable-integration is wrong

### ISSUE THREAD

**Issue by flihp** [tpm2-software/tpm2-abrmd#515]
the configure script reports that this defaults to 'no', but it's lying!

**Comment by williamcroberts** [comment]
Also you always assign integration tests to `TESTS`

**Comment by flihp** [comment]
that's the lie @williamcroberts. Not the most clear / complete bug report I've ever written but since I'm transcribing this from a random email I didn't spend too much time on it. Apologies for that
