### ISSUE TITLE
Dendency Matrix

### ISSUE THREAD

**Issue by YaHosoda** [tpm2-software/tpm2-abrmd#547]
I checked the tpm2-software Version Dependency Matrix
https://github.com/tpm2-software/tpm2-tools/wiki/Dependency-Matrix
According to the matrix, tpm2-tss-1.3 correspondences to tpm2-abrmd-1.2

Then, I have checked tpm2-software RPMs for Linux releases.
The tpm2-tss-1.3 rpm exsits in the following siite
https://rpmfind.net/linux/rpm2html/search.php?query=tpm2-tss

However, the tpm2-abrmd-1.2 seems non-existent.
https://rpmfind.net/linux/rpm2html/search.php?query=tpm2-abrmd

Does anyone know the reason?

**Comment by flihp** [comment]
I don't know much about how the downstream packaging for RPM based systems is organized. That's a pretty old release so I imagine there isn't much incentive to do the packaging work. Assuming there's some relationship between rpmfind.net and Fedora / RedHat @martinezjavier may be able to help?

**Comment by martinezjavier** [comment]
@flihp @YaHosoda sorry I just noticed this mention.

@YaHosoda the tpm2-tss-1.3 RPM is for CentOS 7 and IIRC the latest version in CenTOS 7 is tpm2-abrmd 1.1.0. I think that was due some changes in 1.2.0 that required some SELinux policies changes so updating in a stable distro like CentOS 7 wasn't trivial.

For Fedora we are using the latest stable releases, that is: tpm2-tools-3.1.3, tpm2-tss-devel-2.1.0 and pm2-abrmd-2.0.3. I suggest you to do the same if you are packaging for your distro.
