### ISSUE TITLE
DBus configuration not applied on Ubuntu 18.04 host

### ISSUE THREAD

**Issue by mrcdb** [tpm2-software/tpm2-abrmd#553]
By running the `tpm2-abrmd` installer on a Ubuntu 18.04.1 LTS host, the application does not acquire any presence on the DBus, as shown by the following command:
```
dbus-send --system --dest=org.freedesktop.DBus --type=method_call \
    --print-reply /org/freedesktop/DBus org.freedesktop.DBus.ListNames
```
The DBus configuration is read by default only from the `/etc/dbus-1/system.d/` on the OS, while the `tpm2-abrmd` installer copies the config to `/usr/local/etc/dbus-1/system.d/tpm2-abrmd.conf`. Manually copying the file to the `/etc/dbus-1/system.d/` dir and running `pkill -HUP dbus-daemon` solves the issue.

**Comment by flihp** [comment]
This behavior is as designed and is documented in our INSTALL.md: https://github.com/tpm2-software/tpm2-abrmd/blob/master/INSTALL.md#d-bus-policy---with-dbuspolicydir
