### ISSUE TITLE
Unit tests are failling on s390x architecture

### ISSUE THREAD

**Issue by superm1** [tpm2-software/tpm2-abrmd#566]
Version: 2.0.3-1
This package isn't migrating in Ubuntu since the unit tests are failing on the s390x architecture.  They're also failing in Debian.

Here is the relevant snippet.
```
FAIL: test/connection-manager_unit
==================================

[==========] Running 5 test(s).
[ RUN      ] connection_manager_allocate_test
[       OK ] connection_manager_allocate_test
[ RUN      ] connection_manager_insert_test
[       OK ] connection_manager_insert_test
[ RUN      ] connection_manager_lookup_fd_test
[       OK ] connection_manager_lookup_fd_test
[ RUN      ] connection_manager_lookup_id_test

** (process:9259): WARNING **: 15:26:00.204: connection_manager_lookup_id returned NULL connection
[  ERROR   ] --- 0x14580f4d0 != 0
[   LINE   ] --- test/connection-manager_unit.c:135: error: Failure!
[  FAILED  ] connection_manager_lookup_id_test
[ RUN      ] connection_manager_remove_test
[       OK ] connection_manager_remove_test
[==========] 5 test(s) run.
[  PASSED  ] 4 test(s).
[  FAILED  ] 1 test(s), listed below:
[  FAILED  ] connection_manager_lookup_id_test

 1 FAILED TEST(S)
FAIL test/connection-manager_unit (exit status: 1)
```

The full log is here:
Debian: https://buildd.debian.org/status/fetch.php?pkg=tpm2-abrmd&arch=s390x&ver=2.0.3-1&stamp=1543840485&raw=0
Ubuntu: https://launchpad.net/ubuntu/+source/tpm2-abrmd/2.0.3-1/+build/15734928

**Comment by flihp** [comment]
Thanks for the report. Investigating.

**Comment by flihp** [comment]
Yeah I did something in that test that goes wrong with the endianness changed. Looks like a bug to me.

**Comment by flihp** [comment]
I wanted to test a fix and tried to install a full Debian image under qemu-system-s390x? I ran into the same bugs reported here:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=684909
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=832897
but the suggested work-around in the bug report isn't working for me. Any secret to getting this to work?

**Comment by flihp** [comment]
I'd feel better if I could repro this myself but I've got a candidate fix here: https://github.com/flihp/tpm2-abrmd/tree/bigendian-fix if you've got the cycles to test it. It's very much a fast / dirty fix and I'd like to come up with something more permanent which is why I'd like to be able to repro for testing.

**Comment by flihp** [comment]
Thought about this for a second and, even though I can't confirm this will fix the issue, I'm merging the "fix" mentioned above since it doesn't make things worse. PR is #567. If you can confirm / deny the efficacy of this fix I'd appreciate it.

**Comment by flihp** [comment]
This issue has gone stale. If this hasn't been resolved to your satisfaction please re-open with additional data.
