### ISSUE TITLE
enable probot dco

### ISSUE THREAD

**Issue by flihp** [tpm2-software/tpm2-abrmd#576]
Hi @tstruk. I went into the tpm2-software org interface to try to enable the probot dco app just now but I don't have sufficient permissions. Despite having 'admin' rights on the tpm2-abrmd repo I don't have 'ower' permissions for the org which I guess is required to enable the dco app. Can I get you to do this for me? https://github.com/integration/dco

**Comment by tstruk** [comment]
Done
