### ISSUE TITLE
coveralls not getting pushes

### ISSUE THREAD

**Issue by flihp** [tpm2-software/tpm2-abrmd#580]
looks like this broke around 54035b7ea2d58c8dd2337c032b0d7bc5b4ee4a62

**Comment by joshuagl** [comment]
Check whether an older build is being updated instead. We've been seeing that on the tools for a while, seemingly related to the organisation move, tracked here tpm2-software/tpm2-tools#1114 and filed upstream in a very inactive issue here lemurheavy/coveralls-public#1170

**Comment by flihp** [comment]
resolved in #581
