### ISSUE TITLE
tpm2-tools commands fail on libtss2-esys.so.0: cannot open shared object file: No such file or directory after install

### ISSUE THREAD

**Issue by ambtid** [tpm2-software/tpm2-abrmd#596]
Hi i try to install tpm2-tools but after the install all command fail on this error
`

```
 error while loading shared libraries: libtss2-esys.so.0: cannot open shared object file: No such file or directory
```
i do this steps in the install 

```
git clone https://github.com/tpm2-software/tpm2-tss.git
cd tpm2-tss
./bootstrap
./configure
make check
sudo make install

git clone https://github.com/tpm2-software/tpm2-abrmd.git
cd tpm2-abrmd
./bootstrap
./configure --enable-unit --with-dbuspolicydir=/etc/dbus-1/system.d
dbus-launch make check
sudo make install

git clone https://github.com/tpm2-software/tpm2-tools.git
cd tpm2-tools
./bootstrap
./configure --enable-unit
make check
sudo make install
```
NOTE: i do the same steps before and success to make tpm2-tools work.

**Comment by LSuessmuth** [comment]
Ive got the same problem and would like to know how you fixed this ? Please and Thank you.

**Comment by williamcroberts** [comment]
> Ive got the same problem and would like to know how you fixed this ? Please and Thank you.

what does `pkg-config --libs tss2-esys` output?
what does `ldd $(which tpm2)` output?
what does `ld --verbose | grep SEARCH_DIR` output?
what's your distro?
