### ISSUE TITLE
2.1.1: build fails

### ISSUE THREAD

**Issue by kloczek** [tpm2-software/tpm2-abrmd#601]
<pre>[tkloczko@domek tpm2-abrmd-2.1.1]$ make
make  all-am
make[1]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/tpm2-abrmd-2.1.1&apos;
/bin/sh ./libtool  --tag=CC   --mode=link gcc -Wall -Wextra -Werror -std=gnu99 -Wformat -Wformat-security -Wno-missing-braces -Wno-cast-function-type -fdata-sections -ffunction-sections -fstack-protector-all -fpic -fPIC -Wstrict-overflow=5 -D_GNU_SOURCE -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I./src -I./src/include -I./src -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include  -I/usr/include/gio-unix-2.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -pthread     -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto -Os -Wl,--gc-sections -Wl,--no-undefined -Wl,-z,noexecstack -Wl,-z,now -Wl,-z,relro  -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto -fuse-linker-plugin -o src/tpm2-abrmd src/tabrmd.o -ldbus-1  -lgio-2.0 -lgobject-2.0 -lglib-2.0  -lglib-2.0   -ltss2-sys -ltss2-mu  src/libutil.la -ldl 
libtool: link: gcc -Wall -Wextra -Werror -std=gnu99 -Wformat -Wformat-security -Wno-missing-braces -Wno-cast-function-type -fdata-sections -ffunction-sections -fstack-protector-all -fpic -fPIC -Wstrict-overflow=5 -D_GNU_SOURCE -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I./src -I./src/include -I./src -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -pthread -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto -Os -Wl,--gc-sections -Wl,--no-undefined -Wl,-z -Wl,noexecstack -Wl,-z -Wl,now -Wl,-z -Wl,relro -Wl,-z -Wl,relro -Wl,--as-needed -Wl,-z -Wl,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto -fuse-linker-plugin -o src/tpm2-abrmd src/tabrmd.o  src/.libs/libutil.a -ldbus-1 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -ltss2-sys -ltss2-mu -ldl -pthread
src/tabrmd.c: In function &apos;init_thread_func&apos;:
src/tcti.c:129:12: error: &apos;ctx&apos; may be used uninitialized in this function [-Werror=maybe-uninitialized]
  129 |     return TCTI (g_object_new (TYPE_TCTI,
      |            ^
src/tcti-factory.c:138:24: note: &apos;ctx&apos; was declared here
  138 |     TSS2_TCTI_CONTEXT *ctx;
      |                        ^
lto1: all warnings being treated as errors
lto-wrapper: fatal error: gcc returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
</pre>

**Comment by dilyanpalauzov** [comment]
I cannot reproduce this calling CFLAGS="-flto -Wall -Wextra -Wno-missing-braces -Wno-missing-braces
" ./configure, neither with gcc 8.3.1 8.3.1 20190311 nor with 7.0.1 (tags/RELEASE_701/final).

**Comment by kloczek** [comment]
This was done using gcc 9 from Fedora rawhide which id more sensitive than other compilers.
Probably coverity test will show the same.

**Comment by flihp** [comment]
The comparison to coverity is a good one. The 'ctx' variable is passed by reference to a function that initializes it. The code checks the return value from this function for a success / fail condition and the 'ctx' variable is assumed to have been initialized when the response indicates success. Not the best policy & adding an explicit check for this can't hurt. It does cause a few side effects in the unit tests but fixing that up is just good housekeeping. Looking into that now.

**Comment by flihp** [comment]
I'm hacked up a quick patch on my way out the door tonight: https://github.com/flihp/tpm2-abrmd/tree/tcti-factory_init-null-check If this works for you I'll turn it into a PR.

**Comment by kloczek** [comment]
Hi,

After add https://github.com/flihp/tpm2-abrmd/commit/c3c60743f9224888642ca9448722c3a91709e3ba.patch I was able successfully build tpm2-abrmd

Thx
