### ISSUE TITLE
use AX_IS_RELEASE and AX_CHECK_ENABLE_DEBUG

### ISSUE THREAD

**Issue by flihp** [tpm2-software/tpm2-abrmd#640]
These are some really useful macros that I didn't know existed till @AndreasFuchsSIT pointed them out. Looks like there are two particular benefits:
1) For debugging I've always added the required flags manually through the environment. Having a configure option would be nice.
2) Dialing up warnings & treating warnings as errors in releases has the potential to backfire if the downstream is using a different / newer tool chain. These should only be enabled for builds from git / not a release tarball.

**Comment by flihp** [comment]
see:
https://github.com/tpm2-software/tpm2-tss/commit/4f81110596e814754f20dc6bdee8957617a3f4a9
https://github.com/tpm2-software/tpm2-tss/commit/70c3f9e75ed2f2fa52891a3722cbda1a1befc2a6

**Comment by AndreasFuchsSIT** [comment]
Might wanna think about this too: https://github.com/tpm2-software/tpm2-tss/pull/1447

**Comment by flihp** [comment]
Good looking out @AndreasFuchsSIT. Should save me from a bunch of bug reports.
