### ISSUE TITLE
can not ./configure successfully

### ISSUE THREAD

**Issue by qhbqyj** [tpm2-software/tpm2-abrmd#641]
configure: error: Package requirements (tss2-sys >= 2.0.0) were not met:

No package 'tss2-sys' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables TSS2_SYS_CFLAGS
and TSS2_SYS_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

**Comment by flihp** [comment]
Please read the 'INSTALL` file where we document all build dependencies. The relevant item is unfortunately a bit outdated:
> libsapi and TCTI libraries from https://github.com/tpm2-software/tpm2-tss

`libsapi` is the old name for `libtss2-sys`. I'll get this clarified in the documentation. The URL to the code however is correct.
