### ISSUE TITLE
tpm2-abrmd failed to start

### ISSUE THREAD

**Issue by fl-symbotic** [tpm2-software/tpm2-abrmd#642]
Hi,

I'm using :

# cat /etc/os-release
ID="poky"
NAME="Poky (Yocto Project Reference Distro)"
VERSION="2.5 (sumo)"
VERSION_ID="2.5"
PRETTY_NAME="Poky (Yocto Project Reference Distro) 2.5 (sumo)"
on broadcom Stingray BCM5880X (arm64) platform.
 
I tried to start tpm2-abrmd, I got:

# systemctl restart tpm2-abrmd
Job for tpm2-abrmd.service failed because the control process exited with error code.
See "systemctl status tpm2-abrmd.service" and "journalctl -xe" for details.
# systemctl status tpm2-abrmd.service
? tpm2-abrmd.service - TPM2 Access Broker and Resource Management Daemon
   Loaded: loaded (/lib/systemd/system/tpm2-abrmd.service; disabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2019-06-12 00:03:36 UTC; 1s ago
  Process: 3197 ExecStart=/usr/sbin/tpm2-abrmd (code=exited, status=1/FAILURE)
 Main PID: 3197 (code=exited, status=1/FAILURE)
# journalctl -xe
Jun 12 00:03:46 bcm958802ht16 tpm2-abrmd[3207]: init_thread_func: failed to create TCTI with name "libtss2-tcti-device.so.0" and conf "(null)"
Jun 12 00:03:46 bcm958802ht16 systemd[1]: tpm2-abrmd.service: Main process exited, code=exited, status=1/FAILURE
Jun 12 00:03:46 bcm958802ht16 systemd[1]: tpm2-abrmd.service: Failed with result 'exit-code'.
Jun 12 00:03:46 bcm958802ht16 systemd[1]: Failed to start TPM2 Access Broker and Resource Management Daemon.
-- Subject: Unit tpm2-abrmd.service has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit tpm2-abrmd.service has failed.
--
-- The result is RESULT.
Jun 12 00:03:51 bcm958802ht16 systemd[1]: tpm2-abrmd.service: Service hold-off time over, scheduling restart.
Jun 12 00:03:51 bcm958802ht16 systemd[1]: tpm2-abrmd.service: Scheduled restart job, restart counter is at 5.
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Automatic restarting of the unit tpm2-abrmd.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
Jun 12 00:03:51 bcm958802ht16 systemd[1]: Stopped TPM2 Access Broker and Resource Management Daemon.
-- Subject: Unit tpm2-abrmd.service has finished shutting down
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit tpm2-abrmd.service has finished shutting down.
Jun 12 00:03:51 bcm958802ht16 systemd[1]: Starting TPM2 Access Broker and Resource Management Daemon...
-- Subject: Unit tpm2-abrmd.service has begun start-up
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit tpm2-abrmd.service has begun starting up.
Jun 12 00:03:51 bcm958802ht16 tpm2-abrmd[3211]: ERROR:tcti:src/tss2-tcti/tcti-device.c:399:Tss2_Tcti_Device_Init() Failed to open device file /dev/tpm0: Permission denied
Jun 12 00:03:51 bcm958802ht16 tpm2-abrmd[3211]: failed to initialize device TCTI context: 0xa000a
Jun 12 00:03:51 bcm958802ht16 tpm2-abrmd[3211]: init_thread_func: failed to create TCTI with name "libtss2-tcti-device.so.0" and conf "(null)"
Jun 12 00:03:51 bcm958802ht16 systemd[1]: tpm2-abrmd.service: Main process exited, code=exited, status=1/FAILURE
Jun 12 00:03:51 bcm958802ht16 systemd[1]: tpm2-abrmd.service: Failed with result 'exit-code'.
Jun 12 00:03:51 bcm958802ht16 systemd[1]: Failed to start TPM2 Access Broker and Resource Management Daemon.
-- Subject: Unit tpm2-abrmd.service has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit tpm2-abrmd.service has failed.
--
-- The result is RESULT.
lines 1562-1605/1605 (END)

# cat /usr/lib64/udev/rules.d/tpm-udev.rules
# tpm devices can only be accessed by the tss user but the tss
# group members can access tpmrm devices
KERNEL=="tpm[0-9]*", MODE="0660", OWNER="tss"
KERNEL=="tpmrm[0-9]*", MODE="0660", OWNER="tss", GROUP="tss"

Then I changed /dev/tpm* permission to "tss:tss":
# ls -la /dev/tpm*
crw------- 1 tss tss  10,   224 Jun 12 00:02 /dev/tpm0
crw------- 1 tss tss 253, 65536 Jun 12 00:02 /dev/tpmrm0

When I restarted tpm2-abrmd, I still got 👍 
# systemctl restart tpm2-abrmd
Job for tpm2-abrmd.service failed because a fatal signal was delivered to the control process.
See "systemctl status tpm2-abrmd.service" and "journalctl -xe" for details.
root@bcm958802ht16:~/projects# systemctl status tpm2-abrmd.service
● tpm2-abrmd.service - TPM2 Access Broker and Resource Management Daemon
   Loaded: loaded (/lib/systemd/system/tpm2-abrmd.service; disabled; vendor preset: enab>
   Active: activating (auto-restart) (Result: signal) since Wed 2019-06-12 00:32:05 UTC;>
  Process: 4731 ExecStart=/usr/sbin/tpm2-abrmd (code=killed, signal=TRAP)
 Main PID: 4731 (code=killed, signal=TRAP)
root@bcm958802ht16:~/projects#  systemctl status tpm2-abrmd
● tpm2-abrmd.service - TPM2 Access Broker and Resource Management Daemon
   Loaded: loaded (/lib/systemd/system/tpm2-abrmd.service; disabled; vendor preset: enab>
   Active: activating (auto-restart) (Result: signal) since Wed 2019-06-12 00:34:42 UTC;>
  Process: 4889 ExecStart=/usr/sbin/tpm2-abrmd (code=killed, signal=TRAP)
 Main PID: 4889 (code=killed, signal=TRAP)

Any idea how can I move forward?

Regards,

Frank

**Comment by flihp** [comment]
IMHO the line from the systemd log with the prominent text `ERROR:tcti:src/tss2-tcti/tcti-device.c:399:Tss2_Tcti_Device_Init() Failed to open device file /dev/tpm0: Permission denied` is clear. Check your permissions.
