### ISSUE TITLE
/dev/tpm0: Device or resource busy

### ISSUE THREAD

**Issue by FFY00** [tpm2-software/tpm2-abrmd#654]
Sometimes after starting abrmd we get the following error when some software tries to use the tpm device. As shown in https://github.com/fwupd/fwupd/issues/1353. This requires us to manually restart abrmd to get it working. Is it possible that the tpm device gets stuck in abrmd?

```
/dev/tpm0: Device or resource busy
```

**Comment by diabonas** [comment]
Could you add some more information what steps you took to observe this issue? I couldn't reproduce the error on my own Arch Linux system with tpm2-tss 2.2.3 or tpm2-tss 2.3.1 and tpm2-abrmd 2.2.0 Can you reproduce it with some reliability, or was this a one-off event?

**Comment by diabonas** [comment]
Never mind, for some reason tpm2-abrmd didn't start at all on my system. With tpm2-abrmd, I can reproduce the crash, I will have a look later. For the sake of completeness, here is the stack trace of `fwupdmgr get-devices`, looks very similar to the one you gave in https://github.com/fwupd/fwupd/issues/1353#issuecomment-531289642:
```
#0  0x00007f07ec49a176 n/a (libglib-2.0.so.0)
#1  0x00007f07ec49a3c8 g_logv (libglib-2.0.so.0)
#2  0x00007f07ec49a5b0 g_log (libglib-2.0.so.0)
#3  0x00007f07e565527a Tss2_Tcti_Tabrmd_Init (libtss2-tcti-tabrmd.so.0)
#4  0x00007f07e6463153 n/a (libtss2-esys.so.0)
#5  0x00007f07e646341a n/a (libtss2-esys.so.0)
#6  0x00007f07e64647b9 n/a (libtss2-esys.so.0)
#7  0x00007f07e646498e n/a (libtss2-esys.so.0)
#8  0x00007f07e646419f n/a (libtss2-esys.so.0)
#9  0x00007f07e64643ad n/a (libtss2-esys.so.0)
#10 0x00007f07e64554ad Esys_Initialize (libtss2-esys.so.0)
#11 0x00007f07e5fe7ad8 fu_uefi_pcrs_setup (libfu_plugin_uefi.so)
#12 0x00007f07e5fe5e6f n/a (libfu_plugin_uefi.so)
#13 0x0000560e53a11ce4 fu_device_probe (fwupd)
#14 0x00007f07e5fe2adb fu_plugin_coldplug (libfu_plugin_uefi.so)
#15 0x0000560e53a1b7bb fu_plugin_runner_coldplug (fwupd)
#16 0x0000560e53a287bd n/a (fwupd)
#17 0x0000560e53a334e2 fu_engine_load (fwupd)
#18 0x0000560e53a062d5 main (fwupd)
#19 0x00007f07ebe3cee3 __libc_start_main (libc.so.6)
#20 0x0000560e53a0664e _start (fwupd)
```

**Comment by diabonas** [comment]
There seems to be some weird interaction between the GLib logging system setup by fwupd and the logging used in tpm2-abrmd: even a `g_debug` like the success message in `Tss2_Tcti_Tabrmd_Init` aborts the program, see https://github.com/fwupd/fwupd/issues/1353#issuecomment-531822987. Not sure what the exact issue is, do you have more insights into the logging system @flihp? This might need to get fixed at the fwupd end after all, I don't see any immediate problem with the way tpm2-abrmd uses GLib logging.

**Comment by diabonas** [comment]
Yep, fwupd was setting `g_log_set_fatal_mask (NULL, G_LOG_LEVEL_MASK)`, causing `g_debug` to abort. This is fixed in https://github.com/fwupd/fwupd/pull/1361, no need for any changes on the tpm2-abrmd side.

**Comment by FFY00** [comment]
Thank you for looking into it :grin:

**Comment by diabonas** [comment]
No problem :) I was on the wrong track for quite a while because I thought the reason tpm2-tss 2.3 didn't crash was due to some internal changes in the TCTI handling. I now realise the only reason the new version didn't crash is that it symlinks `libtss2-tcti-default.so` to `libtss2-tcti-device.so` by default, so tpm2-abrmd isn't used at all...

**Comment by FFY00** [comment]
Yeah, I removed `libtss2-tcti-default.so` in the tpm2-tss arch package in community-testing.
