### ISSUE TITLE
systemctl start tpm2-abrmd.service fail

### ISSUE THREAD

**Issue by cui632** [tpm2-software/tpm2-abrmd#655]
Hi:

I am trying to play TPM simulator in ubuntu 16.04. after install TPM Simulator, TPM2TSS, TPM2-abrmd and TPM2-tool successfully, I implement following steps:
1. tpm_server &
2. sudo -u tss tpm2-abrmd --tcti=mssim ,and got next informatioin
--------------------------------------------------------------------------
vincent@cui:~$ sudo -u tss tpm2-abrmd --tcti=mssim

** (process:13733): WARNING **: tcti_conf before: "device:/dev/tpm0"

** (tpm2-abrmd:13733): WARNING **: tcti_conf after: "mssim"

** (tpm2-abrmd:13733): CRITICAL **: Failed to acquire DBus name com.intel.tss2.Tabrmd. UID 998 must be allowed to "own" this name. Check DBus config and check that this is running as user tss or root.

--------------------------------------------------------------------------

next, I try to check tpm2-abrmd service status by following instruction
-------------------------------------------------------------------------
vincent@cui:~$ sudo systemctl status tpm2-abrmd.service
[sudo] password for vincent: 
● tpm2-abrmd.service - TPM2 Access Broker and Resource Management Daemon
   Loaded: loaded (/usr/local/lib/systemd/system/tpm2-abrmd.service; enabled; ve
   Active: activating (auto-restart) (Result: exit-code) since 五 2019-09-20 00:
  Process: 13851 ExecStart=/usr/local/sbin/tpm2-abrmd (code=exited, status=1/FAI
 Main PID: 13851 (code=exited, status=1/FAILURE)

9月 20 00:15:36 cui systemd[1]: Failed to start TPM2 Access Broker and Resource 
9月 20 00:15:36 cui systemd[1]: tpm2-abrmd.service: Unit entered failed state.
9月 20 00:15:36 cui systemd[1]: tpm2-abrmd.service: Failed with result 'exit-cod
lines 1-9/9 (END)
-------------------------------------------------------------------------
next, i try to start the service by following instruction
---------------------------------------------------------------------------
vincent@cui:~$ sudo systemctl start tpm2-abrmd.service
Job for tpm2-abrmd.service failed because the control process exited with error code. See "systemctl status tpm2-abrmd.service" and "journalctl -xe" for details.
-------------------------------------------------------------------------
In order to fix above issue, I look up all materia and method related with tpm2-abrmd service isue. but still fail to fix it. 
Now, I have no way to try.  but I recall clearly that I ever played TPM-TOOL with TPM simulatoer successfully through I did not know how to play it at that time..

Anyone can help to fix it ?

thank you !

Vincent

**Comment by flihp** [comment]
Hi Vincent. This is a dbus issue. The `tss` user must be authorized to 'own' the name `com.intel.tss2.Tabrmd'. Typically this is accomplished when the `tpm2-abrmd.conf` is installed to `dbuspolicy_DATA`. Be sure this file is installed into the right place for your distro (whatever that is).
