### ISSUE TITLE
SELinux Policy failing with multiple denials

### ISSUE THREAD

**Issue by lukehinds** [tpm2-software/tpm2-abrmd#657]
tpm2-abrmd is blocked by the current SELinux policy, this occurs for both using the packaged version `tpm2-abrmd-selinux` and from compiling and applying the policy from this repository `tpm2-abrmd\selinx\*`

```
tpm2-abrmd --version
tpm2-abrmd version 2.2.0
```

Build the policy:

```
git checkout 2.2.0
make -f /usr/share/selinux/devel/Makefile tabrmd.pp
sudo semodule -i tabrmd.pp
restorecon /usr/sbin/tpm2-abrmd
```

```
sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Memory protection checking:     actual (secure)
Max kernel policy version:      31
```

```
systemctl restart tpm2-abrmd
Job for tpm2-abrmd.service failed because the control process exited with error code.
See "systemctl status tpm2-abrmd.service" and "journalctl -xe" for details.
```

```
cat /var/log/audit/audit.log | grep denied
type=AVC msg=audit(1570551860.230:830): avc:  denied  { getattr } for  pid=2369 comm="tpm2-abrmd" path="/etc/resolv.conf" dev="vda1" ino=1573203 scontext=system_u:system_r:tabrmd_t:s0 tcontext=system_u:object_r:net_conf_t:s0 tclass=file permissive=1
type=AVC msg=audit(1570551860.230:831): avc:  denied  { read } for  pid=2369 comm="tpm2-abrmd" name="resolv.conf" dev="vda1" ino=1573203 scontext=system_u:system_r:tabrmd_t:s0 tcontext=system_u:object_r:net_conf_t:s0 tclass=file permissive=1
type=AVC msg=audit(1570551860.230:832): avc:  denied  { open } for  pid=2369 comm="tpm2-abrmd" path="/etc/resolv.conf" dev="vda1" ino=1573203 scontext=system_u:system_r:tabrmd_t:s0 tcontext=system_u:object_r:net_conf_t:s0 tclass=file permissive=1
type=AVC msg=audit(1570551860.231:833): avc:  denied  { create } for  pid=2369 comm="tpm2-abrmd" scontext=system_u:system_r:tabrmd_t:s0 tcontext=system_u:system_r:tabrmd_t:s0 tclass=udp_socket permissive=1
type=AVC msg=audit(1570551860.231:834): avc:  denied  { connect } for  pid=2369 comm="tpm2-abrmd" scontext=system_u:system_r:tabrmd_t:s0 tcontext=system_u:system_r:tabrmd_t:s0 tclass=udp_socket permissive=1
type=AVC msg=audit(1570551860.231:835): avc:  denied  { getattr } for  pid=2369 comm="tpm2-abrmd" laddr=127.0.0.1 lport=53028 faddr=127.0.0.1 fport=2321 scontext=system_u:system_r:tabrmd_t:s0 tcontext=system_u:system_r:tabrmd_t:s0 tclass=udp_socket permissive=1
type=AVC msg=audit(1570551860.231:836): avc:  denied  { create } for  pid=2369 comm="tpm2-abrmd" scontext=system_u:system_r:tabrmd_t:s0 tcontext=system_u:system_r:tabrmd_t:s0 tclass=tcp_socket permissive=1
type=AVC msg=audit(1570551860.231:837): avc:  denied  { connect } for  pid=2369 comm="tpm2-abrmd" scontext=system_u:system_r:tabrmd_t:s0 tcontext=system_u:system_r:tabrmd_t:s0 tclass=tcp_socket permissive=1
type=AVC msg=audit(1570551860.231:838): avc:  denied  { name_connect } for  pid=2369 comm="tpm2-abrmd" dest=2321 scontext=system_u:system_r:tabrmd_t:s0 tcontext=system_u:object_r:unreserved_port_t:s0 tclass=tcp_socket permissive=1
```

**Comment by flihp** [comment]
Queued up for the 2.3.1 release

**Comment by flihp** [comment]
Just set up a Fedora 31 VM, qemu / OVMF, secureboot (to get `/sys/kernel/security/tpm0/binary_bios_measurements`) but I'm not able to reproduce this issue. I built the `tabrmd` policy module the current head of master. The rest of the dependencies came from the Fedora packages. The avcs listed in are not present in the audit log and the daemon is able to run as expected. It looks as though in your example the daemon won't even start if this policy is loaded.

I'm removing this from the 2.3.1 release since the repro failed. Any additional data you can provide about your environment? Those avcs look all wrong since the daemon doesn't touch the network directly. Could be something glib does behind the scenes but binding to an unreserved port looks very wrong to me.

**Comment by lukehinds** [comment]
I think this might be specific when trying to connect to the ibm emulator using `--tcti=mssim`.

I just tested against a HW tpm and there was no issue.

**Comment by trevor-vaughan** [comment]
@lukehinds I agree with this assessment. We use the IBM emulator for acceptance testing and are getting the same issue.

**Comment by trevor-vaughan** [comment]
I'll have a patch for the SELinux policy soon.

**Comment by trevor-vaughan** [comment]
@lukehinds Not sure if you want to go with the `tcs_port_t` connection but it seemed reasonable.

You may want to get a new port added to `selinux-contrib` for remote TCTI connections and switch over to that in the future.

**Comment by lukehinds** [comment]
@flihp, could this be slotted back into 2.3.1 now a fix is available (contingent upon it being merged)

**Comment by flihp** [comment]
Ah this makes a lot more sense now. I didn't pick up on the simulator configuration initially. Will run through the PR and get an RC1 out.
