### ISSUE TITLE
Conflict with TPM 1.2

### ISSUE THREAD

**Issue by khongyew** [tpm2-software/tpm2-abrmd#659]
I'm trying to run the following setup:  
- Ubuntu 19.04
- TPM 2.0 Simulator (ibmtpm1332)
- tpm2-abrmd
    - sudo tpm2-abrmd --allow-root --tcti=mssim
- tpm2_pcrlist 

However, it seems that since my machine has a TPM 1.2 chip, I'm not able to query the TPM 2.0 simulator. When i try to run tpm2_pcrlist, i get this error
> ERROR:sys:src/tss2-sys/api/Tss2_Sys_Execute.c:80:Tss2_Sys_ExecuteFinish() Unsupported device. The device is a TPM 1.2 

How should i configure the setup to ignore the TPM1.2 chip?

**Comment by tstruk** [comment]
Make sure that the tpm2_pcrlist tool talks to the abrmd, and not to the device.
You can do that by passing --tcti=tabrmd:bus_name=com.intel.tss2.Tabrmd flag.
You can also make the tool talk directly to the simulator by passing -Tmssim flag.

**Comment by khongyew** [comment]
After coming across [this link](https://github.com/tpm2-software/tpm2-tss/issues/1435#issuecomment-497942058), I realised that `libtss2-tcti-tabrmd.so` needs to be installed for tpm2_pcrlist tool to connect to tabrmd.

**Comment by mfilipe** [comment]
I am still having this problem:

> ● tpm2-abrmd.service - TPM2 Access Broker and Resource Management Daemon
>    Loaded: loaded (/usr/lib/systemd/system/tpm2-abrmd.service; disabled; vendor preset: disabled)
>    Active: failed (Result: exit-code) since Wed 2020-04-15 15:49:14 -03; 6min ago
>   Process: 4599 ExecStart=/usr/sbin/tpm2-abrmd (code=exited, status=69)
>  Main PID: 4599 (code=exited, status=69)
>  
> abr 15 15:49:14 michel-io tpm2-abrmd[4599]: ERROR:sys:src/tss2-sys/api/Tss2_Sys_Execute.c:114:Tss2_Sys_ExecuteFinish() Unsupported device. The device is a TPM 1.2
> abr 15 15:49:14 michel-io tpm2-abrmd[4599]: Tss2_Sys_Startup returned unexpected RC: 0x80001
> abr 15 15:49:14 michel-io tpm2-abrmd[4599]: access_broker_sent_tpm_startup failed: 0x80001
> abr 15 15:49:14 michel-io tpm2-abrmd[4599]: Failed to GetCapability: TPM2_CAP_TPM_PROPERTIES, TPM2_PT_FIXED: 0x80007
> abr 15 15:49:14 michel-io tpm2-abrmd[4599]: failed to get fixed TPM properties: 0x80007
> abr 15 15:49:14 michel-io tpm2-abrmd[4599]: failed to initialize AccessBroker: 0x80007
> abr 15 15:49:14 michel-io tpm2-abrmd[4599]: g_bus_unown_name: assertion 'owner_id > 0' failed
> abr 15 15:49:14 michel-io systemd[1]: tpm2-abrmd.service: Main process exited, code=exited, status=69/UNAVAILABLE
> abr 15 15:49:14 michel-io systemd[1]: tpm2-abrmd.service: Failed with result 'exit-code'.
> abr 15 15:49:14 michel-io systemd[1]: Failed to start TPM2 Access Broker and Resource Management Daemon.

Fedora 31 with tpm2-abrmd-2.3.1-1.fc31.src.rpm

**Comment by williamcroberts** [comment]
@mfilipe It appears tpm2-abrmd service is being started by dbus, is that correct? You're likely going to need to configure the tpm2-abrmd service file so it point it to the simulator if you want to use that, is that correct?

Looking at:
  - https://www.freedesktop.org/software/systemd/man/systemd.service.html
  - https://www.digitalocean.com/community/tutorials/how-to-use-systemctl-to-manage-systemd-services-and-units

You'll need to modify your service files ExecStart parameter to include the simulator argument:
Something like whats below, or perhaps you could set up an override.conf doing:
```bash
sudo systemctl edit --full tpm2-abrmd.service
```
```
[Unit]
Description=TPM2 Access Broker and Resource Management Daemon

[Service]
Type=dbus
Restart=always
RestartSec=5
BusName=com.intel.tss2.Tabrmd
StandardOutput=syslog
ExecStart=/usr/local/sbin/tpm2-abrmd --tcti=mssim
User=tss

[Install]
WantedBy=multi-user.target
```

I am *not* an expert with anything dbus, so their could be a better way to do this.
