### ISSUE TITLE
tpm2-abrmd.service depends on deprecated systemd-udev-settle.service

### ISSUE THREAD

**Issue by diabonas** [tpm2-software/tpm2-abrmd#704]
Since #675 `tpm2-abrmd.service` depends on `systemd-udev-settle.service`. Unfortunately this service [has been deprecated since systemd version 243](https://github.com/systemd/systemd/pull/12267) and produces the following warning when pulled in:
```
udevadm[1825]: systemd-udev-settle.service is deprecated.
udevadm[1825]: Hint: please fix tpm2-abrmd.service not to pull it in.
```
Not sure what the alternative is, there [seems to be no direct replacement for this service](https://www.freedesktop.org/software/systemd/man/systemd-udev-settle.service.html). Possibly revert #675 and check the device ownership in the daemon instead?

(Reported by @Foxboron)

**Comment by williamcroberts** [comment]
I wonder if we could add the service and tell it not to start and have the udev rule trigger it? I need to find someone who is familiar with this.

**Comment by williamcroberts** [comment]
> I wonder if we could add the service and tell it not to start and have the udev rule trigger it? I need to find someone who is familiar with this.

but then we'd have a weird dependency between the tpm2-tss udev rules and tpm2-abrmd....

**Comment by williamcroberts** [comment]
I wonder if the proper way is to use BindsTo in the service. I wonder if that trigger would occur after chmod.
```
[Unit]
<...>
BindsTo=<DEVICE UNIT HERE>.device
<...>
After=<DEVICE UNIT HERE>.device
```

**Comment by williamcroberts** [comment]
Hrmm, or maybe a `ExecStartPre` where we perform the correct file permission modifications. This way it's cleanly decoupled from udev but not interfering with it.
