### ISSUE TITLE
make check fails test cases

### ISSUE THREAD

**Issue by ambicapramod** [tpm2-software/tpm2-abrmd#715]
As mentioned in the doc, I did the following 

git clone https://github.com/tpm2-software/tpm2-abrmd.git
cd tpm2-abrmd
./bootstrap
./configure --enable-unit --with-dbuspolicydir=/etc/dbus-1/system.d
dbus-launch make check

most of the unit tests are getting failed. 

Attaching the logs.. FYI I'm using kernel 5.6 and fTPM (intel PTT) 

EDIT:
attaching correct log
[test-suite.log](https://github.com/tpm2-software/tpm2-abrmd/files/4491755/test-suite.log)

**Comment by AndreasFuchsSIT** [comment]
```
./test/unit/test_string_bytes: error while loading shared libraries: libtss2-esys.so.1: cannot open shared object file: No such file or directory
FAIL test/unit/test_string_bytes (exit status: 127)
```
You somehow removed libtss2-esys.so.1 from the library search path...

```
/home/intel/tpm2-tools/test/integration/helpers.sh: line 286: tpm_server: command not found
```
You are lacking tpm_server that is needed as mentioned here:
https://github.com/tpm2-software/tpm2-abrmd/blob/master/INSTALL.md#run-integration-tests---enable-integration
