### ISSUE TITLE
tpm2_nvlist is not available

### ISSUE THREAD

**Issue by ambicapramod** [tpm2-software/tpm2-abrmd#717]
I have installed tpm2-tools from in ubuntu 20.0 though apt install

also I have built it from source of master. still, I'm not able to see tpm2_nvlist command and also when I give command 
sudo tpm2_nvdefine -x 0x1500016 -a 0x40000001 -s 64 -t 0x2000A -T device

it shows :
invalid option --x

**Comment by tstruk** [comment]
You may want to open an issue in the tools repo: https://github.com/tpm2-software/tpm2-tools.
This one is for the resource manager.
