### ISSUE TITLE
Failed to acquire DBus name com.intel.tss2.Tabrmd. UID 1000 must be allowed to "own" this name. Check DBus config and check that this is running as user tss or root. #2107

### ISSUE THREAD

**Issue by SchermannR** [tpm2-software/tpm2-abrmd#722]
I followed the installation flow. Anyway, when I'll try to start the tpm2-abrmd with -- allow-root --tcti=mssim I always get following msg:
** (process:13131): WARNING **: 16:15:16.439: tcti_conf before: "device:/dev/tpm0"

** (tpm2-abrmd:13131): WARNING **: 16:15:16.440: tcti_conf after: "mssim"

** (tpm2-abrmd:13131): CRITICAL **: 16:15:16.485: Failed to acquire DBus name com.intel.tss2.Tabrmd. UID 1000 must be allowed to "own" this name. Check DBus config and check that this is running as user tss or root.

TPM module is attached and the ./eltt2 (infineon) test works

**Comment by williamcroberts** [comment]
You need to edit the tpm2-abrmd dbus configuration. My system has it here:
`/etc/dbus-1/system.d/tpm2-abrmd.conf`

This is my config, allows root and myself to take ownership:
```xml
<!DOCTYPE busconfig PUBLIC "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
<busconfig>
  <!-- ../system.conf have denied everything, so we just punch some holes -->
  <policy user="tss">
    <allow own="com.intel.tss2.Tabrmd"/>
  </policy>
  <policy user="root">
    <allow own="com.intel.tss2.Tabrmd"/>
  </policy>
  <policy user="wcrobert">
    <allow own="com.intel.tss2.Tabrmd"/>
  </policy>
  <policy context="default">
    <allow send_destination="com.intel.tss2.Tabrmd"/>
    <allow receive_sender="com.intel.tss2.Tabrmd"/>
  </policy>
</busconfig>
```

**Comment by tstruk** [comment]
Assuming the above helped to solve the issue

**Comment by SchermannR** [comment]
> Assuming the above helped to solve the issue
thx - was a hw-setup issue.
