### ISSUE TITLE
tpm2-tools with tpm2-abrmd

### ISSUE THREAD

**Issue by juncorwu** [tpm2-software/tpm2-abrmd#732]
Hi Sir:

I had a embedded SOC(AM335x) project with SLB9670.
I had enable the driver , list in /dev/tpm0.

My question
If I want to used the following command, did I need to runming tpm2-abrmd??
tpm2_createprimary
tpm2_create
tpm2_load
tpm2_sign
tpm2_verifysignature

I want to sign/verify function.

Thanks,
Juncor

**Comment by williamcroberts** [comment]
Support questions are better asked on the mailing list mentioned in the readme. But you don't need tpm2-abrmd, although it is recomended. You can tell the tools to talk to the device directly with the `--tcti` option

`tpm2_getrandom --tcti=device`

The tcti portion of the manpages is relevant:
https://github.com/tpm2-software/tpm2-tools/blob/master/man/common/tcti.md

For follow ups, please ask on the mailing list, the issue tracker is for actual bugs. Thank you.
