### ISSUE TITLE
How to expose tpm2-abrmd service to the containers.

### ISSUE THREAD

**Issue by pravinrajr9** [tpm2-software/tpm2-abrmd#736]
Hey folks, Is it possible to expose the tpm2-abrmd service to one or more containers?

I have a scenario where agents written using tpm2-tss library needs tpm2-abrmd service. These agents are now containerized and need access to tpm2-abrmd service. But we know only one instance of tpm2-abrmd service can be run as it locks the /dev/tpm0 device and no other process can access /dev/tpm0. 

Is there some way that we can expose the tpm2-abrmd service like socket or dbus and container can make use of them.
In the readme it is clearly mentioned tpm2-abrmd service talks to clients based on combination of pipes and dbus. 
Any Idea how to solve this problem would be greatly appreciated.

**Comment by williamcroberts** [comment]
1. do you have /dev/tpmrm0, containers could just all use that directly by forwarding it to each container.
2. You can also stack resource managers, so in theory, you should be able to in each container fire up tpm2-abrmd and configure its tcti to use /dev/tpmrm0 via the --tcti option. Then each container has abrmd, and the in-kernel rm is managing per-container context. But I would only do this if you need specific tpm2-abrmd features like extended sessions (mostly for tpm2-tools), else, option 1 should work.

**Comment by pravinrajr9** [comment]
@williamcroberts thanks for quick response. yes i do see /dev/tpmrm0 in host system. So without tpm2-abrmd service whether containers can use /dev/tpmrm0 directly how the concurrency is handled then?

I found another option, if we mount /run/dbus/system_bus_socket  as volume on the agents running as containers can talk to tpm2-abrmd service running on host.

**Comment by williamcroberts** [comment]
The same way an RM handles any concurrency. Some process, whether that process is in a container or not, comes to the kernel gets a file descriptor with the in-kernel RM. The RM manages the resources of the TPM seamlessly for each client connected via the fd. This is exactly how tpm2-abrmd does it, except each client is handled over a dbus socket sharing interface.

So you should get similair results sharing each one into the container. You can even stack RM's if you wanted too.

**Comment by pravinrajr9** [comment]
Thanks a lot @williamcroberts
