### ISSUE TITLE
tpm2-abrmd-2.3.3 keeps draining memory

### ISSUE THREAD

**Issue by chenxizf** [tpm2-software/tpm2-abrmd#740]
Hi,

I have tpm2-abrmd-2.3.3 installed. I found it keeps draining memory.

From the log below, we can see the tpm2-abrmd daemon has been running for 1 month, it is using memory = 1.4G now.
The longer the daemon is running, the more memory it is using..
Could anyone help to take a look at this issue?

[root@hostname-1 ~]# service tpm2-abrmd status
Redirecting to /bin/systemctl status tpm2-abrmd.service
● tpm2-abrmd.service - TPM2 Access Broker and Resource Management Daemon
     Loaded: loaded (/usr/lib/systemd/system/tpm2-abrmd.service; enabled; vendor preset: disabled)
     Active: active (running) since Fri 2020-11-13 10:50:53 PST; 1 months 0 days ago
   Main PID: 166534 (tpm2-abrmd)
         IO: 0B read, 0B written
      Tasks: 4
     Memory: 1.4G
        CPU: 1min 40.399s
     CGroup: /system.slice/tpm2-abrmd.service
             └─166534 /usr/sbin/tpm2-abrmd

Warning: journal has been rotated since unit was started, output may be incomplete.

[root@hostname-1~]# rpm -qa | grep tpm2
tpm2-tss-2.4.3.x86_64
tpm2-tools-4.3.0.x86_64
tpm2-abrmd-2.3.3.x86_64

[root@hostname-1 ~]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
... ...

**Comment by williamcroberts** [comment]
Looks like a memory leak... I wonder what's triggering it. IIRC the tests at least run with memory checking and nothing is getting tripped.

**Comment by williamcroberts** [comment]
I wonder if this previously submitted PR fixes your issue:
  - https://github.com/tpm2-software/tpm2-abrmd/pull/733

Can you try applying it and running it and seeing if the issue persists?

**Comment by chenxizf** [comment]
Thanks William for fixing that. Will let you know if it is not working.
