### ISSUE TITLE
CentOS 7 ./configure issues

### ISSUE THREAD

**Issue by amalik18** [tpm2-software/tpm2-abrmd#759]
I'm trying to install `tpm2-tools` on my CentOS 7 machine.

I successfully configure the `tpm2-tss` package but when I get to this, `tpm2-abrmd`, package it continuously throws the following error: 

```
configure: error: Package requirements (tss2-sys >= 2.4.0) were not met:
```

I have looked everywhere for this package but i can not find it. Any help is greatly appreciated.

**Comment by williamcroberts** [comment]
Cent OS seems to have the package in the package manager:
  - https://pkgs.org/download/tpm2-tss
```
CentOS x86_64 Official
--
tpm2-tss-1.4.0-3.el7.i686.rpm | TPM2.0 Software Stack
tpm2-tss-1.4.0-3.el7.x86_64.rpm | TPM2.0 Software Stack
```

Can you not:
```bash
# yum install tpm2-tss
```

per:
https://centos.pkgs.org/7/centos-x86_64/tpm2-tss-1.4.0-3.el7.i686.rpm.html?

You can also install from source from the https://github.com/tpm2-software/tpm2-tss project.

**Comment by williamcroberts** [comment]
Why is this bug on tpm2-abrmd? This seems related to tpm2-tools, just a mistake or are you having tpm2-abrmd issues as well?

**Comment by amalik18** [comment]
I'll try it again this morning. But I was able to properly build `tpm2-tss` but when trying to build `tpm2-abrmd` it throws that error for `tss2-sys`.

**Comment by williamcroberts** [comment]
What's the result of:
```bash
pkg-config --modversion tss2-sys
```

**Comment by amalik18** [comment]
Output of `pkg-config --modversion tss2-sys`:

```
Package tss2-sys was not found in the pkg-config search path.
Perhaps you should add the directory containing `tss2-sys.pc'
to the PKG_CONFIG_PATH environment variable
No package 'tss2-sys' found
```

**Comment by williamcroberts** [comment]
Hrm, when you do a make install, it puts the package config files (.pc) files somewhere on the system. It probably didn't pick the right spot. You can configure this spot during ./configure. You'll see this spot in make install if you look at the output logs.

Try doing a `make uninstall` followed by:
```bash
./configure --prefix=/usr
make install
```

if you're installing to a specialized spot, then you'll want to update the `PKG_CONFIG_PATH`. Or you can just do that and not uninstall-reconfigure and install to the spot chosen by default.

**Comment by amalik18** [comment]
Yep just did all of that in the `tpm2-tss` package, and went back over to `tpm2-abrmd` and it's still throwing the same error.

**Comment by williamcroberts** [comment]
Does this work?
```bash
pkg-config --modversion tss2-sys
```

If that doesn't work, than tpm2-abrmd will throw that error.

**Comment by williamcroberts** [comment]
The `--debug` option can be useful, it dumps out where it's looking for PC files and what it finds.

**Comment by williamcroberts** [comment]
It appears that Cent OS uses a custom package config dir of `/usr/lib64/pkgconfig`.
So in a Cent OS docker container (docker run -it centos:7) I did:
```bash
yum-builddep tpm2-tss
yum install \
  git \
  openssl-devel \
  json-c-devel \
  libcurl-devel \
  make
git clone https://github.com/tpm2-software/tpm2-tss.git
cd tpm2-tss
./bootstrap
./configure --with-pkgconfigdir='/usr/lib64/pkgconfig'
make -j4
make install 2>&1 | tee logz

# now this will work, --debug was useful for figuring out where it was looking.
pkg-config --modversion tss2-sys
3.1.0-dev
```
After that you should be able to build dependent projects.

**Comment by amalik18** [comment]
Yep that did the trick. Thanks a lot. I was able to build `tpm2-tss` and `tpm2-abrmd`. Problem now is with `tpm2-tools` it throws this error when running `./configure`

```
configure: error: Cannot enable -Wbool-compare, consider configuring with --disable-hardening
```

I've tried it with the `--disable-hardening` flag and it's still the same error.

**Comment by williamcroberts** [comment]
in tpm2-tools, that seems like a bug, the PR for it is here:
https://github.com/tpm2-software/tpm2-tools/pull/2325

Do something like:
```bash
wget https://github.com/tpm2-software/tpm2-tools/pull/2325.patch
git am 2325.patch
./bootstrap
./configure
```

However, you'll hit a lot of compilation errors, a PR is forthcoming. Probably tomorrow.

**Comment by williamcroberts** [comment]
If you take the latest from PR https://github.com/tpm2-software/tpm2-tools/pull/2325 it should solve all your issues.

**Comment by tstruk** [comment]
Looks like it's a tools problem now. Closing
