### ISSUE TITLE
arning: .PHONY was already defined in condition TRUE, which includes condition AUTOCONF_CODE_COVER

### ISSUE THREAD

**Issue by kgold2** [tpm2-software/tpm2-abrmd#766]
Ubuntu 16 xenial, x86

When following the instructions to get and install this as a work around, http://ftpmirror.gnu.org/autoconf-archive/autoconf-archive-2019.01.06.tar.xz, bootstrap now says

./bootstrap 
aminclude_static.am:126: warning: .PHONY was already defined in condition TRUE, which includes condition AUTOCONF_CODE_COVERAGE_2019_01_06 ...
Makefile.am:175:   'aminclude_static.am' included from here
Makefile.am:6: ... '.PHONY' previously defined here
Makefile.am:182: warning: AM_DISTCHECK_CONFIGURE_FLAGS multiply defined in condition AUTOCONF_CODE_COVERAGE_2019_01_06 and CODE_COVERAGE_ENABLED ...
aminclude_static.am:100: ... 'AM_DISTCHECK_CONFIGURE_FLAGS' previously defined here
Makefile.am:175:   'aminclude_static.am' included from here

**Comment by williamcroberts** [comment]
This is a harmless warning generated by working around a broken version of autoconf-archive. I wonder if we can just drop the workaround and say you need to have 2021-02-19. But Ubuntu 20.04 doesn't even have it, so it might be premature.

**Comment by kgold2** [comment]
Thanks for the quick response.  The errors looked serious.

This issue seem like it's recurring.  Could you ship the correct files in m4 directly?

**Comment by williamcroberts** [comment]
> Thanks for the quick response. The errors looked serious.

It says, "warning", not "error". Although I can see why the level of concern. We might want to bolster the install docs to say these warnings are harmless.

> 
> This issue seem like it's recurring. Could you ship the correct files in m4 directly?

The issue isn't recurring, If we just drop support for the outdated autoconf-archive versions, this would go away assuming something in autoconf-archive doesn't regress. But then when we ship the autoconf-archive files, then we need to make sure they stay up to date, just one more task to do. Especially when you consider the fixes around the various macros, I don't want to have to track and deal with that when package maintainers provide it.

**Comment by tstruk** [comment]
As explained in https://github.com/tpm2-software/tpm2-tss/issues/2020. This is because the code coverage macros from the autoconf-archive changed in a way that breaks backward compatibility and our workaround to make it work with both old and new version of aminclude_static.am can cause it to emit strange warnings.
