### ISSUE TITLE
make install fails - systemd-sysusers: command not found

### ISSUE THREAD

**Issue by kgold2** [tpm2-software/tpm2-abrmd#768]
Ubuntu 16 xenial.  make install fails with this.  Apparently, there is no systemd-sysusers.

There are other errors, but they may be related to the first one.

make[2]: Entering directory '/home/kgold/tpm2-tss'
(systemd-sysusers && systemd-tmpfiles --create) || \
(    (id -g tss || groupadd -r tss) && (id -u tss || useradd -r -g tss tss) &&     (    (    if [ ! -d /usr/local/var/run/tpm2-tss/eventlog/ ]; then mkdir -p /usr/local/var/run/tpm2-tss/eventlog/; fi) || true) && (    (    if [ ! -d /usr/local/var/lib/tpm2-tss/system/keystore/ ]; then mkdir -p /usr/local/var/lib/tpm2-tss/system/keystore/; fi)) && (all set_fapi_permissions)) || true
/bin/bash: systemd-sysusers: command not found
998
998
/bin/bash: line 1: all: command not found
if [ ! -d "/usr/local/var/run/tpm2-tss/eventlog/" ]; then echo "*** WARNING *** Directory /usr/local/var/run/tpm2-tss/eventlog/ could not be created"; fi
if [ ! -d "/usr/local/var/lib/tpm2-tss/system/keystore/" ]; then echo "*** WARNING *** Directory /usr/local/var/lib/tpm2-tss/system/keystore/ could not be created"; fi
if [ ! -z "" ]; then \
	mv /usr/local/lib/udev/rules.d/tpm-udev.rules /usr/local/lib/udev/rules.d/tpm-udev.rules; \
fi

**Comment by williamcroberts** [comment]
Wrong project, tpm2-abrmd doesn't do this, but you have this filed as bug:
  - https://github.com/tpm2-software/tpm2-tss/issues/2016
