### ISSUE TITLE
Fedora 32 tcti_conf

### ISSUE THREAD

**Issue by kgold2** [tpm2-software/tpm2-abrmd#772]
Installed from yum.  Running as non-root, > tpm2-abrmd --tcti=mssim

** (process:9297): WARNING **: 17:42:36.903: tcti_conf before: "device:/dev/tpm0"
** (tpm2-abrmd:9297): WARNING **: 17:42:36.904: tcti_conf after: "mssim"

1. Where is tcti_conf?  A file?  It would be useful for the message to include the path.
2. It would be useful to describe the configuration in the install instructions.
3. How do I fix this, if it needs to be fixed?

FYI, tpm2_getrandom does work.

**Comment by tstruk** [comment]
> Installed from yum. Running as non-root, > tpm2-abrmd --tcti=mssim
> 
> ** (process:9297): WARNING **: 17:42:36.903: tcti_conf before: "device:/dev/tpm0"
> ** (tpm2-abrmd:9297): WARNING **: 17:42:36.904: tcti_conf after: "mssim"
> 
> 1. Where is tcti_conf?  A file?  It would be useful for the message to include the path.

It's a configuration string. It gets the value of whatever is passed as --tcti="", with "device:/dev/tpm0" being the default.

> 2. It would be useful to describe the configuration in the install instructions.

It is described in its own man page https://github.com/tpm2-software/tpm2-abrmd/blob/master/man/tpm2-abrmd.8.in

> 3. How do I fix this, if it needs to be fixed?

It just a debug message really and has been changed to g_debug() instead of g_warning() in later version.

> 
> FYI, tpm2_getrandom does work.

Does it print error message?

**Comment by kgold2** [comment]
1. I don't see tcti_conf in the man page.
2. I specify --tcti=mssim, but the warning message mentions tpm0.
3. I specify --tcti=mssim, and the warning says there's something after it.
4. It would be useful to explain somewhere what tcti_conf is, and how it relates to the warning.

**Comment by tstruk** [comment]
> 1. I don't see tcti_conf in the man page.
> 2. I specify --tcti=mssim, but the warning message mentions tpm0.
> 3. I specify --tcti=mssim, and the warning says there's something after it.
> 4. It would be useful to explain somewhere what tcti_conf is, and how it relates to the warning.

Ken, tcti_conf is an internal variable (char *) that should never be printed except when in debug mode. This has been fixed in https://github.com/tpm2-software/tpm2-abrmd/commit/acd6c22a0c8b081d73fdd7e38f1af94768de0cea already.
