### ISSUE TITLE
Tss2_Sys_Startup returned unexpected RC: 0x101

### ISSUE THREAD

**Issue by bkgoodman** [tpm2-software/tpm2-abrmd#793]
Cryptic error `Tss2_Sys_Startup returned unexpected RC: 0x101` when trying to launch `tpm2-abrmd` either from command line or as systemctl service.

I am running `swtpm` with a `cuse` device running as `/dev/tpm0` - though according to `strace` - the program hasn't even attempted to open `/dev/tpm0` yet. Same error specifying `-d /dev/tpm0` or not on the command line.

Full error is:

```
** (tpm2-abrmd:2436): WARNING **: 20:35:11.124: Tss2_Sys_Startup returned unexpected RC: 0x101
** (tpm2-abrmd:2436): ERROR **: 20:35:11.124: access_broker_sent_tpm_startup failed: 0x101
```

**Comment by bkgoodman** [comment]
Thanks @williamcroberts !

I think I may have "other" stuff going on here. I am _only_ running with a software TPM (and don't appear to have any physical TPM in this system). For example - I start the sofware TPM like:

`/usr/local/bin/swtpm socket --ctrl type=tcp,port=1234 --tpmstate dir=/tmp/tpm2,mode=0600 --log file=... --tpm2 --pid file=...`

I can minimally verfy that this _appears_ to be working by `telnet`-ing into port `1234` on this system - banging on the keyboard and examining the specified `--log file` (above):

```Error: Unknown command: 0x6173640d
Error: Unknown command: 0x7364660d
Error: Unknown command: 0x7364660d
Error: Unknown command: 0x73640d0a
Error: Unknown command: 0x66617364
Error: Unknown command: 0x61736466
Error: Unknown command: 0x61736466
Error: Unknown command: 0x0d0a0d0a
Error: Unknown command: 0x0d0a0d0a
Error: Unknown command: 0x0d0a0d0a```
```
(expected, given the input). But when I try a "real" TPM command like:

` tpm2_startup -c -T socket:127.0.0.1:1234`
I get a _similar_ error to the OP like:

`ERROR: Failed to initialize tcti context: 0x1`

...but I don't get an actual additional commands logged in the logfile. So invetigating further, if I `strace`, towards the end I see:

```
connect(3, {sa_family=AF_INET, sin_port=htons(1235), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 ECONNREFUSED (Connection refused)
close(3)                                = 0
close(3)                                = -1 EBADF (Bad file descriptor)
close(4)                                = 0
write(2, "ERROR: ", 7ERROR: )                  = 7
write(2, "Failed to initialize tcti contex"..., 39Failed to initialize tcti context: 0x1
```

It was not trying to open port "1234" - but instead "1235"?! Could it be a simple "off-by-one" error? So to accomodate I try...

`strace tpm2_startup -c -T socket:127.0.0.1:1233`

...but now I get:

```
connect(3, {sa_family=AF_INET, sin_port=htons(1234), sin_addr=inet_addr("127.0.0.1")}, 16) = 0
connect(4, {sa_family=AF_INET, sin_port=htons(1233), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 ECONNREFUSED (Connection refused)
close(3)                                = 0
close(3)                                = -1 EBADF (Bad file descriptor)
```

So it's trying to open both the port I specify, _and_ one port below it?!

I have tried so many things - I don't even know where the problem lies. Is it a `tpm2-abrmd` problem" A `swtpm` problem? A `tpm2-tools` problem? Something completely different???????

**Comment by stefanberger** [comment]
> I just recalled something, I think you have to power on the TPM or twiddle it with swtpm_ioctl or swtpm_setup commands. @stefanberger do you have any pointers here?

Here's a pointer: https://github.com/stefanberger/swtpm/wiki/Using-the-Intel-TSS-with-swtpm

**Comment by bkgoodman** [comment]
Ah! Thanks - getting closer? The article you sent alluded to the creation and specification of "control" and "server" ports. When I started as such, my two mystery (tcp) ports were created, my commands connected, and logs (and strace) showed a command being issued, and response returned.

So my command is started as:
`/usr/local/bin/swtpmsocket--tpmstatedir=/tmp/tpm2,mode=0600--logfile=/tmp/swtpm.log,level=5--tpm2--pidfile=/tmp/swtpm.pid--ctrltype=tcp,port=2322--servertype=tcp,port=2321--flagsnot-need-init`

And I issue my "startup" command (which was the same as in the article you specified), like:

`tpm2_startup -c -T socket:127.0.0.1:2321`
...I now get...

`ERROR: Failed to initialize tcti context: 0xa000a`

it DOES seem to be interacting properly w/ swtpm - but doesn't like the response? For example - I see:
```
connect(3, {sa_family=AF_INET, sin_port=htons(2322), sin_addr=inet_addr("127.0.0.1")}, 16) = 0
connect(4, {sa_family=AF_INET, sin_port=htons(2321), sin_addr=inet_addr("127.0.0.1")}, 16) = 0
sendto(3, "\0\0\0\1", 4, MSG_NOSIGNAL, NULL, 0) = 4
recvfrom(3, "\0\0\0\0", 4, 0, NULL, NULL) = 4
sendto(3, "\0\0\0\v", 4, MSG_NOSIGNAL, NULL, 0) = 4
recvfrom(3, "\0\0\377\377", 4, 0, NULL, NULL) = 4
```
...and my swtpm log shows...

```
 Ctrl Cmd: length 4
 00 00 00 01
 Ctrl Rsp: length 8
 00 00 00 00 00 00 FF FF
 ```
 
In desperation, I switched the "server" and "control" ports, but that just made the first recvfrom in the `tpm_setup` infinitiley hang.

So I guess the question now is what does the `ERROR: Failed to initialize tcti context: 0xa000a` mean???

**Comment by stefanberger** [comment]
> The article you sent alluded to the creation and specification of "control" and "server" ports. When I started as such, my two mystery (tcp) ports were created, my commands connected, and logs (and strace) showed a command being issued, and response returned.

One terminal:
```
mkdir /tmp/myvtpm
swtpm socket --tpmstate dir=/tmp/myvtpm --tpm2 --ctrl type=tcp,port=2322 \
   --server type=tcp,port=2321 --flags not-need-init
```

Other terminal:
```
tpm2_startup -c -T swtpm:port=2321
tpm2_pcrread -T swtpm:port=2321
sha1:
  0 : 0x0000000000000000000000000000000000000000
  1 : 0x0000000000000000000000000000000000000000
[...]
```

Works as described and as expected using the swtpm tcti.

**Comment by bkgoodman** [comment]
I tried your commands - but my version of tpm2-tools doesn't appear to support the `-T swtpm` option. This (CentOS 7) system shows:

```
tpm2_startup -v
tool="tpm2_startup" version="3.0.4" tctis="tabrmd,socket,device,"
```

So am going to punt here and claim that this version is too old to support this. I will try it on my Ubuntu 20.04.3 system which shows:

```
tpm2_startup -v
tool="tpm2_startup" version="4.1.1" tctis="libtss2-tctildr" tcti-default=tcti-device
```
So I went through a protracted task of rebuilding `swtpm` for Ubuntu - which appeared to work and run however,  my Ubuntu system's tpm2-tools still didn't seem to like the `swtpm` option as it gives me _different_ errors (than the previous system) such as:

```
tpm2_startup -c  -T swtpm:port=2321
ERROR:tcti:src/tss2-tcti/tctildr.c:418:Tss2_TctiLdr_Initialize_Ex() Failed to instantiate TCTI
tpm2_startup -c  -T socket:127.0.0.1:2321
ERROR:tcti:src/tss2-tcti/tctildr.c:418:Tss2_TctiLdr_Initialize_Ex() Failed to instantiate TCTI
```
...and the dreaded:
```
tpm2_startup -c  -T mssim:host=localhost,port=2321
WARNING:tcti:src/tss2-tcti/tcti-mssim.c:424:simulator_setup() Failed to send MS_SIM_NV_ON platform command.
WARNING:tcti:src/tss2-tcti/tctildr.c:62:tcti_from_init() TCTI init for function 0x7f616d3a83d0 failed with a000a
WARNING:tcti:src/tss2-tcti/tctildr.c:92:tcti_from_info() Could not initialize TCTI named: tcti-socket
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:150:tcti_from_file() Could not initialize TCTI file: mssim
ERROR:tcti:src/tss2-tcti/tctildr.c:418:Tss2_TctiLdr_Initialize_Ex() Failed to instantiate TCTI
ERROR: Could not load tcti, got: "mssim:host=localhost,port=2321"
```
(I am not even sure if the last method here is correct to talk to swtpm - but there was a conspicuous lack of "swtpm" or "socket" commands on the man pages for tpm2 tools under the Ubunto 20 system).

I don't know if all this is because these tpm2 tools are not build with the appropriate "socket" and/or "swtpm" backend device handlers (tctis?) 

So anyway - I went to rebuild all of tpm2-tools - but [got caught with a bug in building tss (https://github.com/tpm2-software/tpm2-tss/issues/2187)- so - I _think_ I need to work that out to rebuild approriate tools to talk to swtpm over the socket? (But not sure???)

I also rebuilt with cuse, but when I run like:

` swtpm cuse -n /dev/tpm0 --tpmstate dir=/tmp/myvtpm --tpm2 --flags not-need-init --log file=/tmp/swtpm.log`

The log file indicates `CUSE TPM successfully initialized.` BUT it never creates the `/dev/tpm0` file - 

but the `tpm2_startup -c` gives:

```
ERROR:tcti:src/tss2-tcti/tcti-device.c:439:Tss2_Tcti_Device_Init() Failed to open device file /dev/tpm0: No such file or directory
```
in addition to a:
```
WARNING:tcti:src/util/io.c:251:socket_connect() Failed to connect to host 127.0.0.1, port 2321: errno 111: Connection refused
```

(among other errors, as it also appears to be trying)

So given the second error - I tried running again with the "socket" interface instead of "cuse", and I noticed the aforementioned "connection refused" message now instead replace with:

```
WARNING:tcti:src/tss2-tcti/tcti-mssim.c:424:simulator_setup() Failed to send MS_SIM_NV_ON platform command.
WARNING:tcti:src/tss2-tcti/tctildr.c:62:tcti_from_init() TCTI init for function 0x7f5e595563d0 failed with a000a
```

**Comment by bkgoodman** [comment]
I made some minor config changes - and am now trying to run with `cuse` -  I seem to have devices like:
```
swtpm cuse -n tpm0 --tpmstate dir=/tmp/myvtpm --tpm2 --log file=/tmp/swtpm.log
 
cat /proc/devices  | grep tpm
241 tpm0
253 tpm

ls -l /dev/tpm0
crw-rw---- 1 tss tss 241, 0 Oct 30 21:30 /dev/tpm0
```

But I still have execution problems:

```
tpm2_startup -c
ERROR:tcti:src/tss2-tcti/tcti-device.c:439:Tss2_Tcti_Device_Init() Failed to open device file /dev/tpmrm0: No such file or directory
WARNING:tcti:src/tss2-tcti/tctildr.c:62:tcti_from_init() TCTI init for function 0x7efe5b6c0fb0 failed with a000a
WARNING:tcti:src/tss2-tcti/tctildr.c:92:tcti_from_info() Could not initialize TCTI named: tcti-device
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:150:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-device.so.0
WARNING:esys:src/tss2-esys/api/Esys_Startup.c:212:Esys_Startup_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_Startup.c:78:Esys_Startup() Esys Finish ErrorCode (0x00000101)
ERROR: Esys_Startup(0x101) - tpm:error(2.0): commands not being accepted because of a TPM failure
ERROR: Unable to run tpm2_startup
```

**Comment by stefanberger** [comment]
The CUSE devices does not create `/dev/tpmrm0`. Use the vtpm_proxy described on that same page instead: https://github.com/stefanberger/swtpm/wiki/Using-the-Intel-TSS-with-swtpm#character-device-using-tpm_vtpm_proxy

**Comment by stefanberger** [comment]
With CUSE it also works I am using `/dev/myvtpm`:

```
sudo swtpm cuse -n myvtpm --tpmstate dir=/tmp/myvtpm --tpm2 --flags not-need-init --log file=/tmp/swtpm.log
```

```
sudo chmod 666 /dev/myvtpm
export TPM2TOOLS_TCTI="device:/dev/myvtpm"
tpm2_startup -c
tpm2_pcrread sha1:10
sha1:
  10: 0x0000000000000000000000000000000000000000
[...]
```

**Comment by bkgoodman** [comment]
That did it! Thanks soooo much!!!!! :-D
